<?php

declare(strict_types=1);

/*
 * Copyright (C) 2026 werkraum-media
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 */

namespace WerkraumMedia\ThueCat\Import\Parser\Entity\Places\Support;

use WerkraumMedia\ThueCat\Import\Parser\Entity\Category\SysCategoryMapper;

// Maps POI @type URIs to the `categories` field; unmapped non-ignored types
// surface as "unmatched" in the import report, the signal to grow the map.
// Shares the `type:` prefix with EventCategoryMapper without colliding:
// category lookup is scoped by storage pid AND configured parent, which differ
// per import configuration.
class PlaceCategoryMapper extends SysCategoryMapper
{
    public function kind(): string
    {
        return 'categories';
    }

    public function sourcePrefix(): string
    {
        return 'type:';
    }

    protected function titleMap(): array
    {
        return [
            'thuecat:AgencyCompany' => 'Agentur',
            'thuecat:ArchaeologicalSite' => 'Archäologische Stätte',
            'thuecat:ArchaeologicalMuseum' => 'Archäologisches Museum',
            'thuecat:Archive' => 'Archiv',
            'thuecat:Arena' => 'Arena',
            'thuecat:AudiovisualTouchpoint' => 'Audiovisueller Touchpoint',
            'thuecat:LookoutTower' => 'Aussichtsturm',
            'schema:ExhibitionEvent' => 'Ausstellung',
            'thuecat:ExhibitionConstruction' => 'Ausstellungsbau',
            'thuecat:AutomobileMuseum' => 'Automobilmuseum',
            'schema:Bakery' => 'Bäckerei',
            'thuecat:BathingLake' => 'Badesee',
            'thuecat:RailwayStation' => 'Bahnhof',
            'thuecat:BallSport' => 'Ballsport',
            'thuecat:Bar' => 'Bar',
            'schema:BarOrPub' => 'Bar oder Kneipe',
            'thuecat:BarefootPark' => 'Barfußpark',
            'thuecat:TreeOrGroupOfTrees' => 'Baum oder Baumgruppe',
            'thuecat:Basin' => 'Becken',
            'schema:LodgingBusiness' => 'Beherbergungsbetrieb',
            'thuecat:SpecialCongressLocation' => 'Besondere Kongresslocation',
            'schema:Library' => 'Bibliothek',
            'thuecat:BeerBar' => 'Bierbar',
            'thuecat:BeerGarden' => 'Biergarten',
            'thuecat:Bistro' => 'Bistro',
            'thuecat:BotanicalGarden' => 'Botanischer Garten',
            'thuecat:BoulderingHall' => 'Boulderhalle',
            'thuecat:BowlRestaurant' => 'Bowl-Restaurant',
            'schema:BowlingAlley' => 'Bowlingbahn',
            'thuecat:GrilledSausageStand' => 'Bratwurststand',
            'schema:Brewery' => 'Brauerei',
            'schema:Distillery' => 'Brennerei',
            'schema:Bridge' => 'Brücke',
            'thuecat:Well' => 'Brunnen',
            'thuecat:Castle' => 'Burg',
            'thuecat:CitizensPark' => 'Bürgerpark',
            'schema:CafeOrCoffeeShop' => 'Café',
            'thuecat:Caterer' => 'Catering',
            'thuecat:Club' => 'Club',
            'thuecat:CoWorkingSpace' => 'Coworking Space',
            'thuecat:Creperie' => 'Crêperie',
            'thuecat:Monument' => 'Denkmal',
            'thuecat:MonumentsOfTradeCraftAndCommerce' => 'Denkmal für Handel, Handwerk und Gewerbe',
            'thuecat:DesignMuseum' => 'Designmuseum',
            'thuecat:Discotheque' => 'Diskothek',
            'thuecat:Dome' => 'Dom',
            'schema:IceCreamShop' => 'Eisdiele',
            'thuecat:RailwayConstruction' => 'Eisenbahnbauwerk',
            'thuecat:EnglishParkLandscapeGarden' => 'Englischer Landschaftsgarten',
            'thuecat:EscapeRoom' => 'Escape Room',
            'thuecat:ProtestantChurch' => 'Evangelische Kirche',
            'thuecat:HalfTimberedHouse' => 'Fachwerkhaus',
            'thuecat:Rock' => 'Fels',
            'thuecat:VacationHome' => 'Ferienhaus',
            'thuecat:FestivalTheater' => 'Festspielhaus',
            'thuecat:Fitness' => 'Fitness',
            'thuecat:FrenchParkGarden' => 'Französischer Garten',
            'thuecat:OutdoorPool' => 'Freibad',
            'thuecat:OpenAirStage' => 'Freilichtbühne',
            'thuecat:ThemePark' => 'Freizeitpark',
            'schema:Cemetery' => 'Friedhof',
            'thuecat:FootballPitch' => 'Fußballplatz',
            'thuecat:Gallery' => 'Galerie',
            'thuecat:Garden' => 'Garten',
            'thuecat:Inn' => 'Gasthaus',
            'thuecat:InnGastronomy' => 'Gasthof',
            'schema:FoodEstablishment' => 'Gastronomiebetrieb',
            'thuecat:Building' => 'Gebäude',
            'thuecat:MemorialSite' => 'Gedenkstätte',
            'thuecat:MemorialSiteBuilding' => 'Gedenkstättengebäude',
            'thuecat:MemorialStone' => 'Gedenkstein',
            'schema:Store' => 'Geschäft',
            'schema:HealthAndBeautyBusiness' => 'Gesundheit und Schönheit',
            'schema:BodyOfWater' => 'Gewässer',
            'schema:GolfCourse' => 'Golfplatz',
            'thuecat:GrillRestaurant' => 'Grillrestaurant',
            'thuecat:IndoorPool' => 'Hallenbad',
            'thuecat:CommerceBuilding' => 'Handelsgebäude',
            'thuecat:Craftsmanship' => 'Handwerkskunst',
            'thuecat:HealingWell' => 'Heilbrunnen',
            'thuecat:MuseumOfLocalHistory' => 'Heimatmuseum',
            'thuecat:Manufacturer' => 'Hersteller',
            'thuecat:HistoricalExhibitionWorkshop' => 'Historische Schauwerkstatt',
            'thuecat:HistoricCemetery' => 'Historischer Friedhof',
            'thuecat:MuseumOfHistory' => 'Historisches Museum',
            'thuecat:HistoricalDistrict' => 'Historisches Viertel',
            'thuecat:FarmRestaurantFarmCafe' => 'Hofrestaurant und Hofcafé',
            'schema:Hotel' => 'Hotel',
            'thuecat:Takeaway' => 'Imbiss zum Mitnehmen',
            'thuecat:IndustrialConstruction' => 'Industriebau',
            'thuecat:InteractiveWorldOfExperience' => 'Interaktive Erlebniswelt',
            'thuecat:CabaretStage' => 'Kabarettbühne',
            'thuecat:CoffeeRoastingHouse' => 'Kaffeerösterei',
            'thuecat:Chapel' => 'Kapelle',
            'thuecat:Cathedral' => 'Kathedrale',
            'schema:CatholicChurch' => 'Katholische Kirche',
            'thuecat:BowlingLane' => 'Kegelbahn',
            'thuecat:SkittleCenter' => 'Kegelzentrum',
            'thuecat:Cinema' => 'Kino',
            'schema:Church' => 'Kirche',
            'thuecat:ClimbingFacility' => 'Kletteranlage',
            'thuecat:Climbing' => 'Klettern',
            'thuecat:ClimbingWall' => 'Kletterwand',
            'thuecat:Monastery' => 'Kloster',
            'thuecat:Pub' => 'Kneipe',
            'thuecat:KneippFacility' => 'Kneippanlage',
            'thuecat:PastryShop' => 'Konditorei',
            'thuecat:ConventionCenter' => 'Kongresszentrum',
            'thuecat:ConcertHall' => 'Konzerthaus',
            'thuecat:HerbGarden' => 'Kräutergarten',
            'thuecat:ArtsAndLeisureCentre' => 'Kultur- und Freizeitzentrum',
            'thuecat:CultureMultipurposeBuilding' => 'Kulturelles Mehrzweckgebäude',
            'thuecat:CultureHistoricalMuseum' => 'Kulturhistorisches Museum',
            'thuecat:CultureEvent' => 'Kulturveranstaltung',
            'thuecat:CulturalCenter' => 'Kulturzentrum',
            'thuecat:ArtMuseum' => 'Kunstmuseum',
            'thuecat:SpaClinicHealthResort' => 'Kurklinik und Heilbad',
            'thuecat:SpaGardens' => 'Kurpark',
            'schema:Landform' => 'Landschaftsform',
            'thuecat:LandscapePark' => 'Landschaftspark',
            'schema:LocalBusiness' => 'Lokales Unternehmen',
            'thuecat:PleasureGarden' => 'Lustgarten',
            'thuecat:Manufacture' => 'Manufaktur',
            'thuecat:Marketplace' => 'Marktplatz',
            'thuecat:Mausoleum' => 'Mausoleum',
            'thuecat:MotorSport' => 'Motorsport',
            'thuecat:MillMonument' => 'Mühlendenkmal',
            'schema:Museum' => 'Museum',
            'thuecat:MuseumWithVariousCollections' => 'Museum mit verschiedenen Sammlungen',
            'thuecat:MuseumCafe' => 'Museumscafé',
            'thuecat:MuseumComplex' => 'Museumskomplex',
            'schema:MusicVenue' => 'Musikspielstätte',
            'thuecat:MuseumOfNaturalHistory' => 'Naturkundemuseum',
            'thuecat:InterestInNature' => 'Natursehenswürdigkeit',
            'thuecat:PublicPark' => 'Öffentlicher Park',
            'schema:PublicSwimmingPool' => 'Öffentliches Schwimmbad',
            'thuecat:Opera' => 'Oper',
            'thuecat:OrthodoxChurch' => 'Orthodoxe Kirche',
            'thuecat:Palais' => 'Palais',
            'schema:Park' => 'Park',
            'schema:ParkingFacility' => 'Parkplatz',
            'thuecat:Patisserie' => 'Patisserie',
            'schema:BedAndBreakfast' => 'Pension',
            'thuecat:Pizzeria' => 'Pizzeria',
            'thuecat:PuppetTheater' => 'Puppentheater',
            'thuecat:Cycling' => 'Radfahren',
            'thuecat:CyclingTrack' => 'Radrennbahn',
            'schema:CityHall' => 'Rathaus',
            'schema:Resort' => 'Resort',
            'schema:Restaurant' => 'Restaurant',
            'thuecat:RevueTheater' => 'Revuetheater',
            'schema:PlaceOfWorship' => 'Sakralbau',
            'thuecat:ReligiousBuilding' => 'Sakralgebäude',
            'thuecat:Sauna' => 'Sauna',
            'thuecat:SaunaClass' => 'Saunabereich',
            'thuecat:SaunaPark' => 'Saunapark',
            'thuecat:ExhibitionMine' => 'Schaubergwerk',
            'thuecat:CaveExhibitionMine' => 'Schaubergwerk in einer Höhle',
            'schema:PerformingArtsTheater' => 'Schauspielhaus',
            'thuecat:Palace' => 'Schloss',
            'thuecat:PalaceAndCastle' => 'Schloss und Burg',
            'thuecat:CastleCafe' => 'Schlosscafé',
            'thuecat:PalaceMuseum' => 'Schlossmuseum',
            'thuecat:CastlePark' => 'Schlosspark',
            'thuecat:PalaceRestaurant' => 'Schlossrestaurant',
            'schema:FastFoodRestaurant' => 'Schnellrestaurant',
            'thuecat:Chocolate' => 'Schokolade',
            'thuecat:PoolClass' => 'Schwimmbad',
            'thuecat:Swimming' => 'Schwimmen',
            'schema:LakeBodyOfWater' => 'See',
            'thuecat:Bench' => 'Sitzbank',
            'thuecat:SkateboardingFacility' => 'Skateanlage',
            'schema:SkiResort' => 'Skigebiet',
            'thuecat:Sculpture' => 'Skulptur',
            'thuecat:SculpturePark' => 'Skulpturenpark',
            'thuecat:SpecialExhibition' => 'Sonderausstellung',
            'thuecat:OtherBuilding' => 'Sonstiges Gebäude',
            'thuecat:Spa' => 'Spa',
            'thuecat:SportsPool' => 'Sportbad',
            'thuecat:SportsBar' => 'Sportsbar',
            'schema:SportsActivityLocation' => 'Sportstätte',
            'schema:SportsClub' => 'Sportverein',
            'thuecat:SportsCentre' => 'Sportzentrum',
            'thuecat:Squash' => 'Squash',
            'thuecat:Stadium' => 'Stadion',
            'schema:StadiumOrArena' => 'Stadion oder Arena',
            'thuecat:CityWall' => 'Stadtmauer',
            'thuecat:CityGate' => 'Stadttor',
            'thuecat:Steakhouse' => 'Steakhaus',
            'thuecat:Stolperstein' => 'Stolperstein',
            'thuecat:BeachSports' => 'Strandsport',
            'thuecat:StreetFoodMarket' => 'Streetfood-Markt',
            'thuecat:Studio' => 'Studio',
            'thuecat:SoupBar' => 'Suppenbar',
            'schema:Synagogue' => 'Synagoge',
            'schema:DaySpa' => 'Tagesspa',
            'thuecat:MeetingCongress' => 'Tagung und Kongress',
            'thuecat:MeetingCongressHotel' => 'Tagungshotel',
            'thuecat:Valley' => 'Tal',
            'thuecat:DanceTheater' => 'Tanztheater',
            'thuecat:Tavern' => 'Taverne',
            'thuecat:TechnicalMuseum' => 'Technikmuseum',
            'thuecat:TechnicalMonument' => 'Technisches Denkmal',
            'schema:Pond' => 'Teich',
            'schema:TennisComplex' => 'Tennisanlage',
            'thuecat:Theater' => 'Theater',
            'thuecat:TheaterEventVenue' => 'Theaterspielstätte',
            'thuecat:TableTennisFacility' => 'Tischtennisanlage',
            'thuecat:TramapolinFacility' => 'Trampolinanlage',
            'thuecat:Tunnel' => 'Tunnel',
            'thuecat:Tower' => 'Turm',
            'thuecat:Gymnasium' => 'Turnhalle',
            'schema:EntertainmentBusiness' => 'Unterhaltungsbetrieb',
            'thuecat:EventHall' => 'Veranstaltungshalle',
            'schema:EventVenue' => 'Veranstaltungsort',
            'thuecat:ConventionEventLocation' => 'Veranstaltungsort für Tagungen',
            'thuecat:Clubhouse' => 'Vereinsheim',
            'thuecat:TrafficBuilding' => 'Verkehrsbauwerk',
            'thuecat:TrafficHistory' => 'Verkehrsgeschichte',
            'schema:GovernmentBuilding' => 'Verwaltungsgebäude',
            'thuecat:Villa' => 'Villa',
            'thuecat:Vinotheque' => 'Vinothek',
            'thuecat:FolkloreMuseum' => 'Volkskundemuseum',
            'schema:LandmarksOrHistoricalBuildings' => 'Wahrzeichen und historische Bauten',
            'thuecat:WakePark' => 'Wakepark',
            'thuecat:Rampart' => 'Wallanlage',
            'thuecat:PlaceOfPilgrimage' => 'Wallfahrtsort',
            'thuecat:WaterBuilding' => 'Wasserbauwerk',
            'thuecat:WaterSki' => 'Wasserski',
            'thuecat:WaterSports' => 'Wassersport',
            'thuecat:WaterStreetBuilding' => 'Wasserstraßenbauwerk',
            'thuecat:BuildingOfDefense' => 'Wehrbau',
            'thuecat:Vineyard' => 'Weinberg',
            'schema:Winery' => 'Weingut',
            'thuecat:WineStore' => 'Weinhandlung',
            'thuecat:WineCellar' => 'Weinkeller',
            'thuecat:WellnessCosmetics' => 'Wellness und Kosmetik',
            'thuecat:MuseumOfScienceMuseumOfNaturalScience' => 'Wissenschaftsmuseum',
            'schema:Zoo' => 'Zoo',
            // Same concept as schema:Zoo but a distinct remote_id, so it gets
            // its own row; editors decide whether to merge.
            'thuecat:Zoo' => 'Zoo2',
        ];
    }

    protected function ignoredValues(): array
    {
        return [
            'schema:Thing',
            'schema:Place',
            'schema:TouristAttraction',
            'ttgds:PointOfInterest',
            'schema:CivicStructure',
            'ttgds:OtherInfraStructure',
            'thuecat:OtherPOI',
            // Structural supertypes with no category meaning of their own.
            'schema:Organization',
            'ttgds:Organization',
            'schema:Event',
            'dcmitype:Event',
            'ttgds:Destination',
            // Compound markers; their constituent types are mapped individually.
            'ttgds:FoodEstablishmentLodgingBusiness',
            'ttgds:Manufacturer',
        ];
    }
}
