<?php

declare(strict_types=1);

use TYPO3\CMS\Core\Resource\FileType;

// TODO: Adjust expectation regarding copyright

return [
    'tx_thuecat_tourist_attraction' => [
        0 => [
            'uid' => '1',
            'pid' => '10',
            'remote_id' => 'https://thuecat.org/resources/attraction-with-media',
            'title' => 'Attraktion mit Bildern',
            // 'mainImage' => 0,
            'images' => 4,
        ],
        1 => [
            'uid' => '2',
            'pid' => '10',
            'remote_id' => 'https://thuecat.org/resources/attraction-with-media',
            'title' => 'Attraction with media',
            // 'media' => '[{"mainImage":false,"type":"image","title":"Bild mit externem Autor","description":"","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/5099196\\/Preview-1280x0\\/image","author":"GivenName FamilyName","copyrightYear":0,"license":{"type":"","author":""}},{"mainImage":false,"type":"image","title":"Bild mit author","description":"","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/5099196\\/Preview-1280x0\\/image","author":"Full Name","copyrightYear":0,"license":{"type":"https:\\/\\/creativecommons.org\\/licenses\\/by\\/4.0\\/","author":""}},{"mainImage":false,"type":"image","title":"Bild mit license author","description":"","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/5099196\\/Preview-1280x0\\/image","author":"","copyrightYear":0,"license":{"type":"https:\\/\\/creativecommons.org\\/licenses\\/by\\/4.0\\/","author":"Autor aus Lizenz"}},{"mainImage":false,"type":"image","title":"Bild mit author und license author","description":"","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/5099196\\/Preview-1280x0\\/image","author":"Full Name","copyrightYear":0,"license":{"type":"https:\\/\\/creativecommons.org\\/licenses\\/by\\/4.0\\/","author":"Autor aus Lizenz"}}]',
        ],
    ],
    'sys_file' => [
        0 => [
            'uid' => 1,
            'pid' => 0,
            'type' => FileType::IMAGE->value,
            'storage' => 1,
            'identifier' => '/editors/thuecat/cc3b031e765a7638b04fc5fd9aeff70abdde342f639e389ad83a151ca4dbaf19.jpeg',
            'extension' => 'jpeg',
            'mime_type' => 'image/jpeg',
            'name' => 'cc3b031e765a7638b04fc5fd9aeff70abdde342f639e389ad83a151ca4dbaf19.jpeg',
            'sha1' => '657a98aa35dad21b6145437f182d98174851bb04',
            'size' => 167998,
            'missing' => 0,
            'identifier_hash' => '6b2cdc95f4cb93ba32ddd26431d6d8a46f2fd9dc',
            'folder_hash' => '8baca3464bf1d9065397866289dd1ee489dbd496',
        ],
        1 => [
            'uid' => 2,
            'pid' => 0,
            'type' => FileType::IMAGE->value,
            'storage' => 1,
            'identifier' => '/editors/thuecat/1d1517409ab350ff208927abc355fbdb480d7b5f2534c8ce676518f0df01e656.jpeg',
            'extension' => 'jpeg',
            'mime_type' => 'image/jpeg',
            'name' => '1d1517409ab350ff208927abc355fbdb480d7b5f2534c8ce676518f0df01e656.jpeg',
            'sha1' => '657a98aa35dad21b6145437f182d98174851bb04',
            'size' => 167998,
            'missing' => 0,
            'identifier_hash' => '2dae4f3631bde1a156843eeda913ddb76b19c804',
            'folder_hash' => '8baca3464bf1d9065397866289dd1ee489dbd496',
        ],
        2 => [
            'uid' => 3,
            'pid' => 0,
            'type' => FileType::IMAGE->value,
            'storage' => 1,
            'identifier' => '/editors/thuecat/faa2741081e0062f6a4edd8e492f9c44b1f22e14d57bdcfbb3b6ca2c8bf9fc02.jpeg',
            'extension' => 'jpeg',
            'mime_type' => 'image/jpeg',
            'name' => 'faa2741081e0062f6a4edd8e492f9c44b1f22e14d57bdcfbb3b6ca2c8bf9fc02.jpeg',
            'sha1' => '657a98aa35dad21b6145437f182d98174851bb04',
            'size' => 167998,
            'missing' => 0,
            'identifier_hash' => 'f796be637a81c9f55cd9a6a9aadae5e596e628d2',
            'folder_hash' => '8baca3464bf1d9065397866289dd1ee489dbd496',
        ],
        3 => [
            'uid' => 4,
            'pid' => 0,
            'type' => FileType::IMAGE->value,
            'storage' => 1,
            'identifier' => '/editors/thuecat/d980f1a42868a7954c87b62f30d863ae01800f4f5febfe0c3942049fdf9d9527.jpeg',
            'extension' => 'jpeg',
            'mime_type' => 'image/jpeg',
            'name' => 'd980f1a42868a7954c87b62f30d863ae01800f4f5febfe0c3942049fdf9d9527.jpeg',
            'sha1' => '657a98aa35dad21b6145437f182d98174851bb04',
            'size' => 167998,
            'missing' => 0,
            'identifier_hash' => 'c4329c3977dc2f1b4f68304c741378c9016d79c8',
            'folder_hash' => '8baca3464bf1d9065397866289dd1ee489dbd496',
        ],
    ],
    'sys_file_metadata' => [
        0 => [
            'uid' => 1,
            'pid' => 0,
            'file' => 1,
            'title' => 'Bild mit externem Autor',
            'width' => 1280,
            'height' => 960,
            'description' => null,
            'alternative' => null,
            'categories' => 0,
            'publisher' => 'thuecat.org',
            'source' => 'https://thuecat.org/resources/image-with-foreign-author',
            'copyright' => '',
            'sys_language_uid' => 0,
            'l10n_parent' => 0,
        ],
        1 => [
            'uid' => 2,
            'pid' => 0,
            'file' => 2,
            'title' => 'Bild mit author',
            'width' => 1280,
            'height' => 960,
            'description' => null,
            'alternative' => null,
            'categories' => 0,
            'publisher' => 'thuecat.org',
            'source' => 'https://thuecat.org/resources/image-with-author-string',
            'copyright' => '',
            'sys_language_uid' => 0,
            'l10n_parent' => 0,
        ],
        2 => [
            'uid' => 3,
            'pid' => 0,
            'file' => 3,
            'title' => 'Bild mit license author',
            'width' => 1280,
            'height' => 960,
            'description' => null,
            'alternative' => null,
            'categories' => 0,
            'publisher' => 'thuecat.org',
            'source' => 'https://thuecat.org/resources/image-with-license-author',
            'copyright' => '',
            'sys_language_uid' => 0,
            'l10n_parent' => 0,
        ],
        3 => [
            'uid' => 4,
            'pid' => 0,
            'file' => 4,
            'title' => 'Bild mit author und license author',
            'width' => 1280,
            'height' => 960,
            'description' => null,
            'alternative' => null,
            'categories' => 0,
            'publisher' => 'thuecat.org',
            'source' => 'https://thuecat.org/resources/image-with-author-and-license-author',
            'copyright' => '',
            'sys_language_uid' => 0,
            'l10n_parent' => 0,
        ],
    ],
    'sys_file_reference' => [
        0 => [
            'uid' => 1,
            'pid' => 10,
            'deleted' => 0,
            'hidden' => 0,
            'uid_local' => 1,
            'uid_foreign' => 1,
            'tablenames' => 'tx_thuecat_tourist_attraction',
            'fieldname' => 'images',
            'sorting_foreign' => 1,
            'title' => '',
            'description' => '',
            'alternative' => '',
            'link' => '',
            'crop' => '',
            'autoplay' => 0,
            'sys_language_uid' => 0,
            'l10n_parent' => 0,
        ],
        1 => [
            'uid' => 2,
            'pid' => 10,
            'deleted' => 0,
            'hidden' => 0,
            'uid_local' => 2,
            'uid_foreign' => 1,
            'tablenames' => 'tx_thuecat_tourist_attraction',
            'fieldname' => 'images',
            'sorting_foreign' => 2,
            'title' => '',
            'description' => '',
            'alternative' => '',
            'link' => '',
            'crop' => '',
            'autoplay' => 0,
            'sys_language_uid' => 0,
            'l10n_parent' => 0,
        ],
        2 => [
            'uid' => 3,
            'pid' => 10,
            'deleted' => 0,
            'hidden' => 0,
            'uid_local' => 3,
            'uid_foreign' => 1,
            'tablenames' => 'tx_thuecat_tourist_attraction',
            'fieldname' => 'images',
            'sorting_foreign' => 3,
            'title' => '',
            'description' => '',
            'alternative' => '',
            'link' => '',
            'crop' => '',
            'autoplay' => 0,
            'sys_language_uid' => 0,
            'l10n_parent' => 0,
        ],
        3 => [
            'uid' => 4,
            'pid' => 10,
            'deleted' => 0,
            'hidden' => 0,
            'uid_local' => 4,
            'uid_foreign' => 1,
            'tablenames' => 'tx_thuecat_tourist_attraction',
            'fieldname' => 'images',
            'sorting_foreign' => 4,
            'title' => '',
            'description' => '',
            'alternative' => '',
            'link' => '',
            'crop' => '',
            'autoplay' => 0,
            'sys_language_uid' => 0,
            'l10n_parent' => 0,
        ],
        4 => [
            'uid' => 5,
            'pid' => 10,
            'deleted' => 0,
            'hidden' => 0,
            'uid_local' => 1,
            'uid_foreign' => 2,
            'tablenames' => 'tx_thuecat_tourist_attraction',
            'fieldname' => 'images',
            'sorting_foreign' => 1,
            'title' => '',
            'description' => '',
            'alternative' => '',
            'link' => '',
            'crop' => '',
            'autoplay' => 0,
            'sys_language_uid' => 1,
            'l10n_parent' => 1,
        ],
        5 => [
            'uid' => 6,
            'pid' => 10,
            'deleted' => 0,
            'hidden' => 0,
            'uid_local' => 2,
            'uid_foreign' => 2,
            'tablenames' => 'tx_thuecat_tourist_attraction',
            'fieldname' => 'images',
            'sorting_foreign' => 2,
            'title' => '',
            'description' => '',
            'alternative' => '',
            'link' => '',
            'crop' => '',
            'autoplay' => 0,
            'sys_language_uid' => 1,
            'l10n_parent' => 2,
        ],
        6 => [
            'uid' => 7,
            'pid' => 10,
            'deleted' => 0,
            'hidden' => 0,
            'uid_local' => 3,
            'uid_foreign' => 2,
            'tablenames' => 'tx_thuecat_tourist_attraction',
            'fieldname' => 'images',
            'sorting_foreign' => 3,
            'title' => '',
            'description' => '',
            'alternative' => '',
            'link' => '',
            'crop' => '',
            'autoplay' => 0,
            'sys_language_uid' => 1,
            'l10n_parent' => 3,
        ],
        7 => [
            'uid' => 8,
            'pid' => 10,
            'deleted' => 0,
            'hidden' => 0,
            'uid_local' => 4,
            'uid_foreign' => 2,
            'tablenames' => 'tx_thuecat_tourist_attraction',
            'fieldname' => 'images',
            'sorting_foreign' => 4,
            'title' => '',
            'description' => '',
            'alternative' => '',
            'link' => '',
            'crop' => '',
            'autoplay' => 0,
            'sys_language_uid' => 1,
            'l10n_parent' => 4,
        ],
    ],
];
