<?php

declare(strict_types=1);

return  [
    'tx_thuecat_import_log' => [
        0 => [
            'uid' => '1',
            'pid' => '0',
            'configuration' => '1',
        ],
    ],
    'tx_thuecat_import_log_entry' => [
        0 => [
            'uid' => '1',
            'pid' => '0',
            'import_log' => '1',
            'record_uid' => '1',
            'table_name' => 'tx_thuecat_organisation',
            'insertion' => '1',
            'errors' => '[]',
        ],
        1 => [
            'uid' => '2',
            'pid' => '0',
            'import_log' => '1',
            'record_uid' => '1',
            'table_name' => 'tx_thuecat_town',
            'insertion' => '1',
            'errors' => '[]',
        ],
        2 => [
            'uid' => '3',
            'pid' => '0',
            'import_log' => '1',
            'record_uid' => '1',
            'table_name' => 'tx_thuecat_parking_facility',
            'insertion' => '1',
            'errors' => '[]',
        ],
        3 => [
            'uid' => '4',
            'pid' => '0',
            'import_log' => '1',
            'record_uid' => '2',
            'table_name' => 'tx_thuecat_parking_facility',
            'insertion' => '0',
            'errors' => '[]',
        ],
        4 => [
            'uid' => '5',
            'pid' => '0',
            'import_log' => '1',
            'record_uid' => '3',
            'table_name' => 'tx_thuecat_parking_facility',
            'insertion' => '0',
            'errors' => '[]',
        ],
        5 => [
            'uid' => '6',
            'pid' => '0',
            'import_log' => '1',
            'record_uid' => '1',
            'table_name' => 'tx_thuecat_tourist_attraction',
            'insertion' => '1',
            'errors' => '[]',
        ],
        6 => [
            'uid' => '7',
            'pid' => '0',
            'import_log' => '1',
            'record_uid' => '2',
            'table_name' => 'tx_thuecat_tourist_attraction',
            'insertion' => '0',
            'errors' => '[]',
        ],
        7 => [
            'uid' => '8',
            'pid' => '0',
            'import_log' => '1',
            'record_uid' => '3',
            'table_name' => 'tx_thuecat_tourist_attraction',
            'insertion' => '1',
            'errors' => '[]',
        ],
        8 => [
            'uid' => '9',
            'pid' => '0',
            'import_log' => '1',
            'record_uid' => '4',
            'table_name' => 'tx_thuecat_tourist_attraction',
            'insertion' => '0',
            'errors' => '[]',
        ],
        9 => [
            'uid' => '10',
            'pid' => '0',
            'import_log' => '1',
            'record_uid' => '5',
            'table_name' => 'tx_thuecat_tourist_attraction',
            'insertion' => '0',
            'errors' => '[]',
        ],
    ],
    'tx_thuecat_organisation' => [
        0 => [
            'uid' => '1',
            'pid' => '10',
            'remote_id' => 'https://thuecat.org/resources/018132452787-ngbe',
            'title' => 'Erfurt Tourismus und Marketing GmbH',
        ],
    ],
    'tx_thuecat_town' => [
        0 => [
            'uid' => '1',
            'pid' => '10',
            'remote_id' => 'https://thuecat.org/resources/043064193523-jcyt',
            'title' => 'Erfurt',
            'managed_by' => '1',
        ],
    ],
    'tx_thuecat_parking_facility' => [
        0 => [
            'uid' => '1',
            'pid' => '10',
            'sys_language_uid' => '0',
            'remote_id' => 'https://thuecat.org/resources/396420044896-drzt',
            'title' => 'Parkhaus Domplatz',
            'managed_by' => '1',
        ],
        1 => [
            'uid' => '2',
            'pid' => '10',
            'sys_language_uid' => '1',
            'remote_id' => 'https://thuecat.org/resources/396420044896-drzt',
            'title' => 'Car park Domplatz',
            'managed_by' => '1',
        ],
        2 => [
            'uid' => '3',
            'pid' => '10',
            'sys_language_uid' => '2',
            'remote_id' => 'https://thuecat.org/resources/396420044896-drzt',
            'title' => 'Parking Domplatz',
            'managed_by' => '1',
        ],
    ],
    'tx_thuecat_tourist_attraction' => [
        0 => [
            'uid' => '1',
            'pid' => '10',
            'sys_language_uid' => '0',
            'remote_id' => 'https://thuecat.org/resources/835224016581-dara',
            'title' => 'Dom St. Marien',
            'managed_by' => '1',
            'town' => '1',
        ],
        1 => [
            'uid' => '2',
            'pid' => '10',
            'sys_language_uid' => '1',
            'remote_id' => 'https://thuecat.org/resources/835224016581-dara',
            'title' => 'Cathedral of St. Mary',
            'managed_by' => '1',
            'town' => '1',
        ],
        2 => [
            'uid' => '3',
            'pid' => '10',
            'sys_language_uid' => '0',
            'remote_id' => 'https://thuecat.org/resources/165868194223-zmqf',
            'title' => 'Alte Synagoge',
            'managed_by' => '1',
            'town' => '1',
        ],
        3 => [
            'uid' => '4',
            'pid' => '10',
            'sys_language_uid' => '1',
            'remote_id' => 'https://thuecat.org/resources/165868194223-zmqf',
            'title' => 'Old Synagogue',
            'managed_by' => '1',
            'town' => '1',
        ],
        4 => [
            'uid' => '5',
            'pid' => '10',
            'sys_language_uid' => '2',
            'remote_id' => 'https://thuecat.org/resources/165868194223-zmqf',
            'title' => 'La vieille synagogue',
            'managed_by' => '1',
            'town' => '1',
        ],
    ],
];
