<?php

declare(strict_types=1);

return [
    'tx_thuecat_tourist_attraction' => [
        0 => [
            'uid' => '1',
            'pid' => '10',
            'sys_language_uid' => '0',
            'l18n_parent' => '0',
            'l10n_source' => '0',
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/835224016581-dara',
            'title' => 'Dom St. Marien',
            'managed_by' => '1',
            'town' => '1',
            'address' => '{"street":"Domstufen 1","zip":"99084","city":"Erfurt","email":"dominformation@domberg-erfurt.de","phone":"+49 361 6461265","fax":"","geo":{"latitude":50.975955358589545,"longitude":11.023667024961856}}',
            'offers' => '[]',
        ],
        1 => [
            'uid' => '2',
            'pid' => '10',
            'sys_language_uid' => '1',
            'l18n_parent' => '1',
            'l10n_source' => '1',
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/835224016581-dara',
            'title' => 'Cathedral of St. Mary',
            'managed_by' => '1',
            'town' => '1',
            'address' => '{"street":"Domstufen 1","zip":"99084","city":"Erfurt","email":"dominformation@domberg-erfurt.de","phone":"+49 361 6461265","fax":"","geo":{"latitude":50.975955358589545,"longitude":11.023667024961856}}',
            'offers' => '[]',
        ],
        2 => [
            'uid' => '3',
            'pid' => '10',
            'sys_language_uid' => '0',
            'l18n_parent' => '0',
            'l10n_source' => '0',
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/165868194223-zmqf',
            'title' => 'Alte Synagoge',
            'managed_by' => '1',
            'town' => '1',
            'address' => '{"street":"Waagegasse 8","zip":"99084","city":"Erfurt","email":"altesynagoge@erfurt.de","phone":"+49 361 6551520","fax":"+49 361 6551669","geo":{"latitude":50.978765,"longitude":11.029133}}',
            'offers' => '[{"types":["GuidedTourOffer"],"title":"F\\u00fchrungen","description":"Immer samstags, um 11:15 Uhr findet eine \\u00f6ffentliche F\\u00fchrung durch das Museum statt. Dauer etwa 90 Minuten","prices":[{"title":"Erwachsene","description":"","price":8,"currency":"EUR","rule":"PerPerson"},{"title":"Erm\\u00e4\\u00dfigt","description":"als erm\\u00e4\\u00dfigt gelten schulpflichtige Kinder, Auszubildende, Studierende, Rentner\\/-innen, Menschen mit Behinderungen, Inhaber Sozialausweis der Landeshauptstadt Erfurt","price":5,"currency":"EUR","rule":"PerPerson"}]},{"types":["EntryOffer"],"title":"Eintritt","description":"Schulklassen und Kitagruppen im Rahmen des Unterrichts: Eintritt frei\\nAn jedem ersten Dienstag im Monat: Eintritt frei","prices":[{"title":"Erm\\u00e4\\u00dfigt","description":"als erm\\u00e4\\u00dfigt gelten schulpflichtige Kinder, Auszubildende, Studierende, Rentner\\/-innen, Menschen mit Behinderungen, Inhaber Sozialausweis der Landeshauptstadt Erfurt","price":5,"currency":"EUR","rule":"PerPerson"},{"title":"Familienkarte","description":"","price":17,"currency":"EUR","rule":"PerGroup"},{"title":"ErfurtCard","description":"","price":14.9,"currency":"EUR","rule":"PerPackage"},{"title":"Erwachsene","description":"","price":8,"currency":"EUR","rule":"PerPerson"}]}]',
        ],
        3 => [
            'uid' => '4',
            'pid' => '10',
            'sys_language_uid' => '1',
            'l18n_parent' => '3',
            'l10n_source' => '3',
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/165868194223-zmqf',
            'title' => 'Old Synagogue',
            'managed_by' => '1',
            'town' => '1',
            'address' => '{"street":"Waagegasse 8","zip":"99084","city":"Erfurt","email":"altesynagoge@erfurt.de","phone":"+49 361 6551520","fax":"+49 361 6551669","geo":{"latitude":50.978765,"longitude":11.029133}}',
            'offers' => '[{"types":["GuidedTourOffer"],"title":"","description":"","prices":[{"title":"","description":"","price":8,"currency":"EUR","rule":"PerPerson"},{"title":"","description":"","price":5,"currency":"EUR","rule":"PerPerson"}]},{"types":["EntryOffer"],"title":"","description":"","prices":[{"title":"","description":"","price":5,"currency":"EUR","rule":"PerPerson"},{"title":"","description":"","price":17,"currency":"EUR","rule":"PerGroup"},{"title":"","description":"","price":14.9,"currency":"EUR","rule":"PerPackage"},{"title":"","description":"","price":8,"currency":"EUR","rule":"PerPerson"}]}]',
        ],
        4 => [
            'uid' => '5',
            'pid' => '10',
            'sys_language_uid' => '2',
            'l18n_parent' => '3',
            'l10n_source' => '3',
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/165868194223-zmqf',
            'title' => 'La vieille synagogue',
            'managed_by' => '1',
            'town' => '1',
            'address' => '{"street":"Waagegasse 8","zip":"99084","city":"Erfurt","email":"altesynagoge@erfurt.de","phone":"+49 361 6551520","fax":"+49 361 6551669","geo":{"latitude":50.978765,"longitude":11.029133}}',
            'offers' => '[{"types":["GuidedTourOffer"],"title":"","description":"","prices":[{"title":"","description":"","price":8,"currency":"EUR","rule":"PerPerson"},{"title":"","description":"","price":5,"currency":"EUR","rule":"PerPerson"}]},{"types":["EntryOffer"],"title":"","description":"","prices":[{"title":"","description":"","price":5,"currency":"EUR","rule":"PerPerson"},{"title":"","description":"","price":17,"currency":"EUR","rule":"PerGroup"},{"title":"","description":"","price":14.9,"currency":"EUR","rule":"PerPackage"},{"title":"","description":"","price":8,"currency":"EUR","rule":"PerPerson"}]}]',
        ],
        5 => [
            'uid' => '6',
            'pid' => '10',
            'sys_language_uid' => '0',
            'l18n_parent' => '0',
            'l10n_source' => '0',
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/215230952334-yyno',
            'title' => 'Krämerbrücke',
            'managed_by' => '1',
            'town' => '1',
            'address' => '{"street":"Benediktsplatz 1","zip":"99084","city":"Erfurt","email":"service@erfurt-tourismus.de","phone":"+49 361 66 400","fax":"","geo":{"latitude":50.978772,"longitude":11.031622}}',
            'offers' => '[]',
        ],
        6 => [
            'uid' => '7',
            'pid' => '10',
            'sys_language_uid' => '1',
            'l18n_parent' => '6',
            'l10n_source' => '6',
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/215230952334-yyno',
            'title' => 'Merchants\' Bridge',
            'managed_by' => '1',
            'town' => '1',
            'address' => '{"street":"Benediktsplatz 1","zip":"99084","city":"Erfurt","email":"service@erfurt-tourismus.de","phone":"+49 361 66 400","fax":"","geo":{"latitude":50.978772,"longitude":11.031622}}',
            'offers' => '[]',
        ],
        7 => [
            'uid' => '8',
            'pid' => '10',
            'sys_language_uid' => '2',
            'l18n_parent' => '6',
            'l10n_source' => '6',
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/215230952334-yyno',
            'title' => 'Pont de l\'épicier',
            'managed_by' => '1',
            'town' => '1',
            'address' => '{"street":"Benediktsplatz 1","zip":"99084","city":"Erfurt","email":"service@erfurt-tourismus.de","phone":"+49 361 66 400","fax":"","geo":{"latitude":50.978772,"longitude":11.031622}}',
            'offers' => '[]',
        ],
    ],
];
