<?php

declare(strict_types=1);

// The middle image 400s: two files, two references per language, record intact.
return [
    'tx_thuecat_tourist_attraction' => [
        0 => [
            'uid' => '1',
            'pid' => '10',
            'remote_id' => 'https://thuecat.org/resources/attraction-with-failing-image',
            'title' => 'Attraktion mit fehlendem Bild',
            'main_image' => '0',
            'media_files' => '2',
        ],
        1 => [
            'uid' => '2',
            'pid' => '10',
            'remote_id' => 'https://thuecat.org/resources/sibling-attraction-under-same-root',
            'title' => 'Nachbarattraktion',
            'main_image' => '0',
            'media_files' => '1',
        ],
        2 => [
            'uid' => '3',
            'pid' => '10',
            'remote_id' => 'https://thuecat.org/resources/attraction-with-failing-image',
            'title' => 'Attraction with failing image',
            'main_image' => '0',
            'media_files' => '2',
        ],
        3 => [
            'uid' => '4',
            'pid' => '10',
            'remote_id' => 'https://thuecat.org/resources/sibling-attraction-under-same-root',
            'title' => 'Sibling attraction',
            'main_image' => '0',
            'media_files' => '1',
        ],
    ],
    'sys_file' => [
        0 => [
            'uid' => '2',
            'storage' => '1',
            'type' => '2',
            'extension' => 'jpg',
            'mime_type' => 'image/jpeg',
            'name' => 'image_6ab24be70ef3f2e8.jpg',
            'identifier' => '/thuecat/image_6ab24be70ef3f2e8.jpg',
        ],
        1 => [
            'uid' => '3',
            'storage' => '1',
            'type' => '2',
            'extension' => 'jpg',
            'mime_type' => 'image/jpeg',
            'name' => 'image_707f417a26e68985.jpg',
            'identifier' => '/thuecat/image_707f417a26e68985.jpg',
        ],
        2 => [
            'uid' => '4',
            'storage' => '1',
            'type' => '2',
            'extension' => 'jpg',
            'mime_type' => 'image/jpeg',
            'name' => 'image_34ca8e6e645bbbc5.jpg',
            'identifier' => '/thuecat/image_34ca8e6e645bbbc5.jpg',
        ],
    ],
    'sys_file_reference' => [
        0 => [
            'uid' => '1',
            'uid_local' => '2',
            'uid_foreign' => '1',
            'tablenames' => 'tx_thuecat_tourist_attraction',
            'fieldname' => 'media_files',
            'sorting_foreign' => '1',
            'title' => 'Bild vor dem Fehler',
        ],
        1 => [
            'uid' => '2',
            'uid_local' => '3',
            'uid_foreign' => '1',
            'tablenames' => 'tx_thuecat_tourist_attraction',
            'fieldname' => 'media_files',
            'sorting_foreign' => '2',
            'title' => 'Bild nach dem Fehler',
        ],
        2 => [
            'uid' => '3',
            'uid_local' => '4',
            'uid_foreign' => '2',
            'tablenames' => 'tx_thuecat_tourist_attraction',
            'fieldname' => 'media_files',
            'sorting_foreign' => '1',
            'title' => 'Bild der Nachbarattraktion',
        ],
        3 => [
            'uid' => '4',
            'uid_local' => '2',
            'uid_foreign' => '3',
            'tablenames' => 'tx_thuecat_tourist_attraction',
            'fieldname' => 'media_files',
            'sorting_foreign' => '1',
            'title' => '[Translate to English:] Bild vor dem Fehler',
        ],
        4 => [
            'uid' => '5',
            'uid_local' => '3',
            'uid_foreign' => '3',
            'tablenames' => 'tx_thuecat_tourist_attraction',
            'fieldname' => 'media_files',
            'sorting_foreign' => '2',
            'title' => '[Translate to English:] Bild nach dem Fehler',
        ],
        5 => [
            'uid' => '6',
            'uid_local' => '4',
            'uid_foreign' => '4',
            'tablenames' => 'tx_thuecat_tourist_attraction',
            'fieldname' => 'media_files',
            'sorting_foreign' => '1',
            'title' => '[Translate to English:] Bild der Nachbarattraktion',
        ],
    ],
];
