<?php

declare(strict_types=1);

return [
    'tx_thuecat_tourist_attraction' => [
        0 => [
            'uid' => '1',
            'pid' => '10',
            'remote_id' => 'https://thuecat.org/resources/attraction-with-media',
            'title' => 'Attraktion mit Bildern',
            'main_image' => '0',
            'media_files' => '4',
        ],
        1 => [
            'uid' => '2',
            'pid' => '10',
            'remote_id' => 'https://thuecat.org/resources/attraction-with-media',
            'title' => 'Attraction with media',
            'main_image' => '0',
            'media_files' => '4',
        ],
    ],
    'sys_file' => [
        0 => [
            'uid' => '2',
            'storage' => '1',
            'type' => '2',
            'extension' => 'jpg',
            'mime_type' => 'image/jpeg',
            'name' => 'image-with-foreign-author_Bild-mit-externem-Autor.jpg',
            'identifier' => '/thuecat/image-with-foreign-author_Bild-mit-externem-Autor.jpg',
        ],
        1 => [
            'uid' => '3',
            'storage' => '1',
            'type' => '2',
            'extension' => 'jpg',
            'mime_type' => 'image/jpeg',
            'name' => 'image-with-author-string_Bild-mit-author.jpg',
            'identifier' => '/thuecat/image-with-author-string_Bild-mit-author.jpg',
        ],
        2 => [
            'uid' => '4',
            'storage' => '1',
            'type' => '2',
            'extension' => 'jpg',
            'mime_type' => 'image/jpeg',
            'name' => 'image-with-license-author_Bild-mit-license-author.jpg',
            'identifier' => '/thuecat/image-with-license-author_Bild-mit-license-author.jpg',
        ],
        3 => [
            'uid' => '5',
            'storage' => '1',
            'type' => '2',
            'extension' => 'jpg',
            'mime_type' => 'image/jpeg',
            'name' => 'image-with-author-and-license-author_Bild-mit-author-und-license-author.jpg',
            'identifier' => '/thuecat/image-with-author-and-license-author_Bild-mit-author-und-license-author.jpg',
        ],
    ],
    'sys_file_reference' => [
        0 => [
            'uid' => '1',
            'uid_local' => '2',
            'uid_foreign' => '1',
            'tablenames' => 'tx_thuecat_tourist_attraction',
            'fieldname' => 'media_files',
            'sorting_foreign' => '1',
            'title' => 'Bild mit externem Autor',
        ],
        1 => [
            'uid' => '2',
            'uid_local' => '3',
            'uid_foreign' => '1',
            'tablenames' => 'tx_thuecat_tourist_attraction',
            'fieldname' => 'media_files',
            'sorting_foreign' => '2',
            'title' => 'Bild mit author',
        ],
        2 => [
            'uid' => '3',
            'uid_local' => '4',
            'uid_foreign' => '1',
            'tablenames' => 'tx_thuecat_tourist_attraction',
            'fieldname' => 'media_files',
            'sorting_foreign' => '3',
            'title' => 'Bild mit license author',
        ],
        3 => [
            'uid' => '4',
            'uid_local' => '5',
            'uid_foreign' => '1',
            'tablenames' => 'tx_thuecat_tourist_attraction',
            'fieldname' => 'media_files',
            'sorting_foreign' => '4',
            'title' => 'Bild mit author und license author',
        ],
        4 => [
            'uid' => '5',
            'uid_local' => '2',
            'uid_foreign' => '2',
            'tablenames' => 'tx_thuecat_tourist_attraction',
            'fieldname' => 'media_files',
            'sorting_foreign' => '1',
        ],
        5 => [
            'uid' => '6',
            'uid_local' => '3',
            'uid_foreign' => '2',
            'tablenames' => 'tx_thuecat_tourist_attraction',
            'fieldname' => 'media_files',
            'sorting_foreign' => '2',
        ],
        6 => [
            'uid' => '7',
            'uid_local' => '4',
            'uid_foreign' => '2',
            'tablenames' => 'tx_thuecat_tourist_attraction',
            'fieldname' => 'media_files',
            'sorting_foreign' => '3',
        ],
        7 => [
            'uid' => '8',
            'uid_local' => '5',
            'uid_foreign' => '2',
            'tablenames' => 'tx_thuecat_tourist_attraction',
            'fieldname' => 'media_files',
            'sorting_foreign' => '4',
        ],
    ],
];
