<?php

declare(strict_types=1);

return [
    'tx_thuecat_tourist_attraction' => [
        [
            'uid' => 1,
            'pid' => 10,
            'sys_language_uid' => 0,
            'l18n_parent' => 0,
            'l10n_source' => 0,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/835224016581-dara',
            'title' => 'Dom St. Marien',
            'managed_by' => 1,
            'town' => 1,
            'address' => '{"remote_id":"genid-7bb7d92bd6624bdf84634c86e8acdbb4-b0","street":"Domstufen 1","zip":"99084","city":"Erfurt","email":"dominformation@domberg-erfurt.de","phone":"+49 361 6461265","geo":{"latitude":50.975955358589545,"longitude":11.023667024961856}}',
            'offers' => null,
            'opening_hours' => null,
            'media' => '[{"mainImage":true,"type":"image","title":"Erfurt-Dom und Severikirche-beleuchtet.jpg","description":"","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/5159216\\/Preview-1280x0\\/image","author":"","copyrightYear":2016,"license":{"type":"https:\\/\\/creativecommons.org\\/licenses\\/by\\/4.0\\/","author":""}},{"mainImage":false,"type":"image","title":"Erfurt-Dom-und-Severikirche.jpg","description":"Sicht auf Dom St. Marien, St. Severikirche sowie die davor liegenden Klostergeb\\u00e4ude und einem Ausschnitt des Biergartens umgeben von einem d\\u00e4mmerungsverf\\u00e4rten Himmel","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/5159186\\/Preview-1280x0\\/image","author":"","copyrightYear":2020,"license":{"type":"https:\\/\\/creativecommons.org\\/licenses\\/by\\/4.0\\/","author":""}},{"mainImage":false,"type":"image","title":"Erfurt-Dom und Severikirche-beleuchtet.jpg","description":"","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/5159216\\/Preview-1280x0\\/image","author":"","copyrightYear":2016,"license":{"type":"https:\\/\\/creativecommons.org\\/licenses\\/by\\/4.0\\/","author":""}}]',
            'description' => 'Über eine 70-stufige Freitreppe gelangt man vom Domplatz auf den Domberg mit seinen beiden ehemaligen Stiftskirchen. Der Dom, mit hochgotischem Chor, romanischem Turmbereich und spätgotischer Westhalle, ist Nachfolger des 724 von Rom veranlassten Sakralbaus. Er war die Hauptkirche des 742 von Bischof Bonifatius gegründeten Bistums Erfurt und während des Mittelalters bis in das frühe 19. Jahrhundert Sitz des Collegiatstifts St. Marien. 1507 erhielt Martin Luther hier die Priesterweihe.
Der ursprünglich romanische Kirchenbau wurde in der Zeit der Gotik entscheidend umgebaut. Besonders sehenswert sind die gotischen Chorfenster, das umfängliche Chorgestühl (14. Jhd.) sowie die romanischen Skulpturen einer thronenden Madonna und eines monumentalen Kerzenträgers im Innenraum. Berühmt ist er auch wegen der „Gloriosa“, der mit 2,56 m Durchmesser größten freischwingenden mittelalterlichen Glocke der Welt.
Das Ensemble von Dom und Severikirche bildet eine imposante Kulisse für die jährlich im Sommer stattfindenden DomStufen-Festspiele.',
            'slogan' => null,
            'accessibility_specification' => null,
            'parking_facility_near_by' => '1',
        ],
        [
            'uid' => 2,
            'pid' => 10,
            'sys_language_uid' => 0,
            'l18n_parent' => 0,
            'l10n_source' => 0,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/508431710173-wwne',
            'title' => 'Domplatz Erfurt',
            'managed_by' => 1,
            'town' => 1,
            'address' => '{"remote_id":"genid-443f86d2acdc469dad4b3588d31d0c49-b0","street":"Domplatz","zip":"99084","city":"Erfurt","geo":{"latitude":50.97694183291915,"longitude":11.023886024076779}}',
            'offers' => null,
            'opening_hours' => null,
            'media' => null,
            'description' => 'Der Domplatz ist der wohl bekannteste Platz Erfurts, nicht zuletzt wegen des imposanten Ensembles aus dem Dom St. Marien und der St. Severikirche. Am Fuße des Petersbergs und am Rand der Altstadt gelegen, bietet er viel Platz für allerlei Feste und Veranstaltungen. 
Montag bis Samstag findet hier außerdem der Wochenmarkt statt.
Im Osten und im Süden des Domplatzes laden eine Vielzahl Cafés und Restaurants zum Verweilen und Genießen ein.',
            'slogan' => null,
            'accessibility_specification' => null,
            'parking_facility_near_by' => '1',
        ],
        [
            'uid' => 3,
            'pid' => 10,
            'sys_language_uid' => 0,
            'l18n_parent' => 0,
            'l10n_source' => 0,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/165868194223-zmqf',
            'title' => 'Alte Synagoge',
            'managed_by' => 1,
            'town' => 1,
            'address' => '{"remote_id":"genid-28b33237f71b41e3ad54a99e1da769b9-b0","street":"Waagegasse 8","zip":"99084","city":"Erfurt","email":"altesynagoge@erfurt.de","phone":"+49 361 6551520","fax":"+49 361 6551669","geo":{"latitude":50.978765,"longitude":11.029133}}',
            'offers' => '[{"types":["GuidedTourOffer"],"title":"F\\u00fchrungen","description":"Immer samstags, um 11:15 Uhr findet eine \\u00f6ffentliche F\\u00fchrung durch das Museum statt. Dauer etwa 90 Minuten","prices":[{"title":"Erwachsene","description":"","price":8,"currency":"EUR","rule":"PerPerson"},{"title":"Erm\\u00e4\\u00dfigt","description":"als erm\\u00e4\\u00dfigt gelten schulpflichtige Kinder, Auszubildende, Studierende, Rentner\\/-innen, Menschen mit Behinderungen, Inhaber Sozialausweis der Landeshauptstadt Erfurt","price":5,"currency":"EUR","rule":"PerPerson"}]},{"types":["EntryOffer"],"title":"Eintritt","description":"Schulklassen und Kitagruppen im Rahmen des Unterrichts: Eintritt frei\\nAn jedem ersten Dienstag im Monat: Eintritt frei","prices":[{"title":"Erm\\u00e4\\u00dfigt","description":"als erm\\u00e4\\u00dfigt gelten schulpflichtige Kinder, Auszubildende, Studierende, Rentner\\/-innen, Menschen mit Behinderungen, Inhaber Sozialausweis der Landeshauptstadt Erfurt","price":5,"currency":"EUR","rule":"PerPerson"},{"title":"Familienkarte","description":"","price":17,"currency":"EUR","rule":"PerGroup"},{"title":"ErfurtCard","description":"","price":14.9,"currency":"EUR","rule":"PerPackage"},{"title":"Erwachsene","description":"","price":8,"currency":"EUR","rule":"PerPerson"}]}]',
            'opening_hours' => null,
            'media' => '[{"mainImage":true,"type":"image","title":"Erfurt-Alte Synagoge","description":"Frontaler Blick auf die Hausfront\\/Hausfassade im Innenhof mit Zugang \\u00fcber die Waagegasse","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/5099196\\/Preview-1280x0\\/image","author":"","copyrightYear":2009,"license":{"type":"https:\\/\\/creativecommons.org\\/licenses\\/by\\/4.0\\/","author":"F:\\\\Bilddatenbank\\\\Museen und Ausstellungen\\\\Alte Synagoge"}},{"mainImage":false,"type":"image","title":"Erfurt-Alte Synagoge","description":"Frontaler Blick auf die Hausfront\\/Hausfassade im Innenhof mit Zugang \\u00fcber die Waagegasse","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/5099196\\/Preview-1280x0\\/image","author":"","copyrightYear":2009,"license":{"type":"https:\\/\\/creativecommons.org\\/licenses\\/by\\/4.0\\/","author":"F:\\\\Bilddatenbank\\\\Museen und Ausstellungen\\\\Alte Synagoge"}}]',
            'description' => 'Beispiel Beschreibung',
            'slogan' => 'Highlight',
            'accessibility_specification' => '{"accessibilityCertificationStatus":"AccessibilityChecked","certificationAccessibilityDeaf":"None","certificationAccessibilityMental":"None","certificationAccessibilityPartiallyDeaf":"None","certificationAccessibilityPartiallyVisual":"Info","certificationAccessibilityVisual":"None","certificationAccessibilityWalking":"Info","certificationAccessibilityWheelchair":"Info","accessibilitySearchCriteria":{"facilityAccessibilityWalking":["AllRoomsStepFreeAccess","HingedGrabRailToilet","LateralAccessibleToilet","StepFreeAccess","ToiletsPeopleWithDisabilities","NinetyCMWidthPassageWays","SpecialOffersWalkingImpairment","SpecialOffersWheelchairUsers"],"facilityAccessibilityVisual":["AssistanceDogsWelcome","VisuallyContrastingStepEdges","OffersInPictoralLanguage","SpecialOffersBlindPeople","SpecialOffersVisualImpairment","TactileOffers"],"facilityAccessibilityDeaf":["AudioInductionLoop","SpecialOffersHearingImpairment"],"facilityAccessibilityMental":["InformationWithPictogramsOrPictures"]},"shortDescriptionAccessibilityDeaf":"Deutsche Beschreibung von shortDescriptionAccessibilityDeaf","shortDescriptionAccessibilityMental":"Deutsche Beschreibung von shortDescriptionAccessibilityMental","shortDescriptionAccessibilityVisual":"Deutsche Beschreibung von shortDescriptionAccessibilityVisual","shortDescriptionAccessibilityWalking":"Deutsche Beschreibung von shortDescriptionAccessibilityWalking"}',
            'parking_facility_near_by' => '1',
        ],
        [
            'uid' => 4,
            'pid' => 10,
            'sys_language_uid' => 0,
            'l18n_parent' => 0,
            'l10n_source' => 0,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/497839263245-edbm',
            'title' => 'Waagegasse Erfurt',
            'managed_by' => 1,
            'town' => 1,
            'address' => '{"remote_id":"genid-4205641db5894928b636fbc984941a62-b0","street":"Waagegasse","zip":"99084","city":"Erfurt","geo":{"latitude":50.97868297541305,"longitude":11.027608736826844}}',
            'offers' => null,
            'opening_hours' => null,
            'media' => null,
            'description' => 'Die Waagegasse mag zunächst unspektakulär erscheinen, ist aber eine bemerkenswert alte und für die Erfurter Geschichte sehr bedeutsame Straße. Denn hier wurden sämtliche Händler, die Erfurt passieren und/oder in Erfurt handeln wollten, durchgeführt. Die Straße ist genauso breit wie ein Fuhrwerk, sodass jeder einzeln durchgeschleust werden konnte. Jede Kutsche wurde hier gewogen, je nach Wert Steuern erhoben und die Ware wurde drei Tage in den heute noch sichtbaren Stapelhäusern gelagert.
Heute spielt die Waagegasse vor allem als "Schleichweg" zwischen Michaelis- und Allerheiligenstraße, als Zugang zur Alten Synagoge und natürlich bei zahlreichen Stadtführungen eine Rolle.',
            'slogan' => null,
            'accessibility_specification' => null,
            'parking_facility_near_by' => '1',
        ],
        [
            'uid' => 5,
            'pid' => 10,
            'sys_language_uid' => 0,
            'l18n_parent' => 0,
            'l10n_source' => 0,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/215230952334-yyno',
            'title' => 'Krämerbrücke',
            'managed_by' => 1,
            'town' => 1,
            'address' => '{"remote_id":"genid-a45a5606cd074d86bf242c9464d84171-b0","street":"Benediktsplatz 1","zip":"99084","city":"Erfurt","email":"service@erfurt-tourismus.de","phone":"+49 361 66 400","geo":{"latitude":50.978772,"longitude":11.031622}}',
            'offers' => null,
            'opening_hours' => null,
            'media' => '[{"mainImage":true,"type":"image","title":"Erfurt-Kraemerbruecke-11.jpg","description":"Kr\\u00e4merbr\\u00fccke in Erfurt","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/134362\\/Preview-1280x0\\/image","author":"Florian Trykowski","copyrightYear":2019,"license":{"type":"https:\\/\\/creativecommons.org\\/publicdomain\\/zero\\/1.0\\/deed.de","author":"https:\\/\\/home.ttgnet.de\\/ttg\\/projekte\\/10006\\/90136\\/Projektdokumente\\/Vergabe%20Rahmenvertrag%20Fotoproduktion"}},{"mainImage":false,"type":"image","title":"Erfurt-Kraemerbruecke.jpg","description":"Kr\\u00e4merbr\\u00fccke in Erfurt","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/134288\\/Preview-1280x0\\/image","author":"Florian Trykowski","copyrightYear":2019,"license":{"type":"https:\\/\\/creativecommons.org\\/publicdomain\\/zero\\/1.0\\/deed.de","author":"https:\\/\\/home.ttgnet.de\\/ttg\\/projekte\\/10006\\/90136\\/Projektdokumente\\/Vergabe%20Rahmenvertrag%20Fotoproduktion"}},{"mainImage":false,"type":"image","title":"Erfurt-Kraemerbruecke-11.jpg","description":"Kr\\u00e4merbr\\u00fccke in Erfurt","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/134362\\/Preview-1280x0\\/image","author":"Florian Trykowski","copyrightYear":2019,"license":{"type":"https:\\/\\/creativecommons.org\\/publicdomain\\/zero\\/1.0\\/deed.de","author":"https:\\/\\/home.ttgnet.de\\/ttg\\/projekte\\/10006\\/90136\\/Projektdokumente\\/Vergabe%20Rahmenvertrag%20Fotoproduktion"}},{"mainImage":false,"type":"image","title":"Erfurt-Kraemerbruecke-13.jpg","description":"Ansicht der Kr\\u00e4merbr\\u00fccke, Erfurt","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/652340\\/Preview-1280x0\\/image","author":"Florian Trykowski","copyrightYear":2019,"license":{"type":"https:\\/\\/creativecommons.org\\/publicdomain\\/zero\\/1.0\\/deed.de","author":"https:\\/\\/home.ttgnet.de\\/ttg\\/projekte\\/10006\\/90136\\/Projektdokumente\\/Vergabe%20Rahmenvertrag%20Fotoproduktion"}}]',
            'description' => 'Ein bekanntes Wahrzeichen Erfurts ist die Krämerbrücke, die längste bebaute und bewohnte Brücke Europas.Die Krämerbrücke wurde zu Beginn aus Holz und 1325 aus Stein erbaut. Zunächst war die 120 m lange Brücke mit 62 schmalen Häusern bebaut. Später wurden einige der Häuser auf nun mehr 32 zusammengefasst. An beiden Enden der Brücke standen zwei Brückenkopfkirchen. Heute existiert nur noch eine der beiden, die östlich gelegene Ägidienkirche.Auf der Krämerbrücke kann man in Galerien und Boutiquen sehr schön bummeln gehen. Man kann Thüringer Handwerksmeistern bei ihrer Arbeit über die Schulter schauen. Keramik, Porzellan und Holzschnitzereien, Blaudruck und Lauschaer Glas sind beliebte Souvenirs. Cafès, Weinhändler und Feinkostgeschäfte mit Thüringer Spezialitäten laden zum Verweilen ein.',
            'slogan' => null,
            'accessibility_specification' => '{"accessibilityCertificationStatus":"AccessibilityChecked","certificationAccessibilityDeaf":"None","certificationAccessibilityMental":"None","certificationAccessibilityPartiallyDeaf":"None","certificationAccessibilityPartiallyVisual":"Info","certificationAccessibilityVisual":"None","certificationAccessibilityWalking":"Info","certificationAccessibilityWheelchair":"Info","accessibilitySearchCriteria":{"facilityAccessibilityWalking":["AllRoomsStepFreeAccess","HingedGrabRailToilet","LateralAccessibleToilet","StepFreeAccess","ToiletsPeopleWithDisabilities","NinetyCMWidthPassageWays","SpecialOffersWalkingImpairment","SpecialOffersWheelchairUsers"],"facilityAccessibilityVisual":["AssistanceDogsWelcome","VisuallyContrastingStepEdges","OffersInPictoralLanguage","SpecialOffersBlindPeople","SpecialOffersVisualImpairment","TactileOffers"],"facilityAccessibilityDeaf":["AudioInductionLoop","SpecialOffersHearingImpairment"],"facilityAccessibilityMental":["InformationWithPictogramsOrPictures"]},"shortDescriptionAccessibilityDeaf":"Deutsche Beschreibung von shortDescriptionAccessibilityDeaf","shortDescriptionAccessibilityMental":"Deutsche Beschreibung von shortDescriptionAccessibilityMental","shortDescriptionAccessibilityVisual":"Deutsche Beschreibung von shortDescriptionAccessibilityVisual","shortDescriptionAccessibilityWalking":"Deutsche Beschreibung von shortDescriptionAccessibilityWalking"}',
            'parking_facility_near_by' => '1,2',
        ],
        [
            'uid' => 6,
            'pid' => 10,
            'sys_language_uid' => 0,
            'l18n_parent' => 0,
            'l10n_source' => 0,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/052821473718-oxfq',
            'title' => 'Wenigemarkt Erfurt',
            'managed_by' => 1,
            'town' => 1,
            'address' => '{"remote_id":"genid-0f944fd40aa04d3d85374be0fe18c485-b0","street":"Wenigermarkt","zip":"99084","city":"Erfurt","geo":{"latitude":50.97859562923252,"longitude":11.031994832523964}}',
            'offers' => null,
            'opening_hours' => null,
            'media' => null,
            'description' => 'Der Wenigemarkt befindet sich am östlichen Zugang der Krämerbrücke. Hier finden Sie eine Vielzahl Cafés und Restaurants, die zum Verbleiben und Entspannen einladen.',
            'slogan' => null,
            'accessibility_specification' => null,
            'parking_facility_near_by' => '1,2',
        ],
        [
            'uid' => 7,
            'pid' => 10,
            'sys_language_uid' => 2,
            'l18n_parent' => 1,
            'l10n_source' => 1,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/835224016581-dara',
            'title' => 'Dom St. Marien',
            'managed_by' => 1,
            'town' => 1,
            'address' => '{"remote_id":"genid-7bb7d92bd6624bdf84634c86e8acdbb4-b0","street":"Domstufen 1","zip":"99084","city":"Erfurt","email":"dominformation@domberg-erfurt.de","phone":"+49 361 6461265","geo":{"latitude":50.975955358589545,"longitude":11.023667024961856}}',
            'offers' => null,
            'opening_hours' => null,
            'media' => '[{"mainImage":true,"type":"image","title":"Erfurt-Dom und Severikirche-beleuchtet.jpg","description":"","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/5159216\\/Preview-1280x0\\/image","author":"","copyrightYear":2016,"license":{"type":"https:\\/\\/creativecommons.org\\/licenses\\/by\\/4.0\\/","author":""}},{"mainImage":false,"type":"image","title":"Erfurt-Dom-und-Severikirche.jpg","description":"Sicht auf Dom St. Marien, St. Severikirche sowie die davor liegenden Klostergeb\\u00e4ude und einem Ausschnitt des Biergartens umgeben von einem d\\u00e4mmerungsverf\\u00e4rten Himmel","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/5159186\\/Preview-1280x0\\/image","author":"","copyrightYear":2020,"license":{"type":"https:\\/\\/creativecommons.org\\/licenses\\/by\\/4.0\\/","author":""}},{"mainImage":false,"type":"image","title":"Erfurt-Dom und Severikirche-beleuchtet.jpg","description":"","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/5159216\\/Preview-1280x0\\/image","author":"","copyrightYear":2016,"license":{"type":"https:\\/\\/creativecommons.org\\/licenses\\/by\\/4.0\\/","author":""}}]',
            'description' => 'Über eine 70-stufige Freitreppe gelangt man vom Domplatz auf den Domberg mit seinen beiden ehemaligen Stiftskirchen. Der Dom, mit hochgotischem Chor, romanischem Turmbereich und spätgotischer Westhalle, ist Nachfolger des 724 von Rom veranlassten Sakralbaus. Er war die Hauptkirche des 742 von Bischof Bonifatius gegründeten Bistums Erfurt und während des Mittelalters bis in das frühe 19. Jahrhundert Sitz des Collegiatstifts St. Marien. 1507 erhielt Martin Luther hier die Priesterweihe.
Der ursprünglich romanische Kirchenbau wurde in der Zeit der Gotik entscheidend umgebaut. Besonders sehenswert sind die gotischen Chorfenster, das umfängliche Chorgestühl (14. Jhd.) sowie die romanischen Skulpturen einer thronenden Madonna und eines monumentalen Kerzenträgers im Innenraum. Berühmt ist er auch wegen der „Gloriosa“, der mit 2,56 m Durchmesser größten freischwingenden mittelalterlichen Glocke der Welt.
Das Ensemble von Dom und Severikirche bildet eine imposante Kulisse für die jährlich im Sommer stattfindenden DomStufen-Festspiele.',
            'slogan' => null,
            'accessibility_specification' => null,
            'parking_facility_near_by' => '1',
        ],
        [
            'uid' => 8,
            'pid' => 10,
            'sys_language_uid' => 2,
            'l18n_parent' => 2,
            'l10n_source' => 2,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/508431710173-wwne',
            'title' => 'Place de la cathédrale et rue commerçante',
            'managed_by' => 1,
            'town' => 1,
            'address' => '{"remote_id":"genid-443f86d2acdc469dad4b3588d31d0c49-b0","street":"Domplatz","zip":"99084","city":"Erfurt","geo":{"latitude":50.97694183291915,"longitude":11.023886024076779}}',
            'offers' => null,
            'opening_hours' => null,
            'media' => null,
            'description' => 'Avec pour toile de fond l’imposante cathédrale Notre-Dame et l’église Saint-Sévère, la place de la cathédrale vous attire avec ses charmants petits magasins et un large choix en terme de gastronomie.
Des marchands de la région vous proposent chaque jour, de 7 à 14h, des produits frais comme des fruits et légumes, de la viande et des saucisses ainsi que de nombreuses gourmandises.
',
            'slogan' => null,
            'accessibility_specification' => null,
            'parking_facility_near_by' => '1',
        ],
        [
            'uid' => 9,
            'pid' => 10,
            'sys_language_uid' => 2,
            'l18n_parent' => 3,
            'l10n_source' => 3,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/165868194223-zmqf',
            'title' => 'La vieille synagogue',
            'managed_by' => 1,
            'town' => 1,
            'address' => '{"remote_id":"genid-28b33237f71b41e3ad54a99e1da769b9-b0","street":"Waagegasse 8","zip":"99084","city":"Erfurt","email":"altesynagoge@erfurt.de","phone":"+49 361 6551520","fax":"+49 361 6551669","geo":{"latitude":50.978765,"longitude":11.029133}}',
            'offers' => '[{"types":["GuidedTourOffer"],"title":"","description":"","prices":[{"title":"","description":"","price":8,"currency":"EUR","rule":"PerPerson"},{"title":"","description":"","price":5,"currency":"EUR","rule":"PerPerson"}]},{"types":["EntryOffer"],"title":"","description":"","prices":[{"title":"","description":"","price":5,"currency":"EUR","rule":"PerPerson"},{"title":"","description":"","price":17,"currency":"EUR","rule":"PerGroup"},{"title":"","description":"","price":14.9,"currency":"EUR","rule":"PerPackage"},{"title":"","description":"","price":8,"currency":"EUR","rule":"PerPerson"}]}]',
            'opening_hours' => null,
            'media' => '[{"mainImage":true,"type":"image","title":"Erfurt-Alte Synagoge","description":"Frontaler Blick auf die Hausfront\\/Hausfassade im Innenhof mit Zugang \\u00fcber die Waagegasse","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/5099196\\/Preview-1280x0\\/image","author":"","copyrightYear":2009,"license":{"type":"https:\\/\\/creativecommons.org\\/licenses\\/by\\/4.0\\/","author":"F:\\\\Bilddatenbank\\\\Museen und Ausstellungen\\\\Alte Synagoge"}},{"mainImage":false,"type":"image","title":"Erfurt-Alte Synagoge","description":"Frontaler Blick auf die Hausfront\\/Hausfassade im Innenhof mit Zugang \\u00fcber die Waagegasse","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/5099196\\/Preview-1280x0\\/image","author":"","copyrightYear":2009,"license":{"type":"https:\\/\\/creativecommons.org\\/licenses\\/by\\/4.0\\/","author":"F:\\\\Bilddatenbank\\\\Museen und Ausstellungen\\\\Alte Synagoge"}}]',
            'description' => 'La vieille synagogue (datant des années 1100) est la synagogue la plus vieille d’Europe totalement conservée, dans laquelle est exposé un trésor datant des 13/14èmes siècles avec une alliance juive unique et des écritures hébraïques (datant des 12ème, 13ème et 14èmes siècles). Après la redécouverte du Mikwé, Erfurt abrite des témoins uniques et fascinants d’une communauté juive médiévale. ',
            'slogan' => 'Highlight',
            'accessibility_specification' => '{"accessibilityCertificationStatus":"AccessibilityChecked","certificationAccessibilityDeaf":"None","certificationAccessibilityMental":"None","certificationAccessibilityPartiallyDeaf":"None","certificationAccessibilityPartiallyVisual":"Info","certificationAccessibilityVisual":"None","certificationAccessibilityWalking":"Info","certificationAccessibilityWheelchair":"Info","accessibilitySearchCriteria":{"facilityAccessibilityWalking":["AllRoomsStepFreeAccess","HingedGrabRailToilet","LateralAccessibleToilet","StepFreeAccess","ToiletsPeopleWithDisabilities","NinetyCMWidthPassageWays","SpecialOffersWalkingImpairment","SpecialOffersWheelchairUsers"],"facilityAccessibilityVisual":["AssistanceDogsWelcome","VisuallyContrastingStepEdges","OffersInPictoralLanguage","SpecialOffersBlindPeople","SpecialOffersVisualImpairment","TactileOffers"],"facilityAccessibilityDeaf":["AudioInductionLoop","SpecialOffersHearingImpairment"],"facilityAccessibilityMental":["InformationWithPictogramsOrPictures"]}}',
            'parking_facility_near_by' => '1',
        ],
        [
            'uid' => 10,
            'pid' => 10,
            'sys_language_uid' => 2,
            'l18n_parent' => 4,
            'l10n_source' => 4,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/497839263245-edbm',
            'title' => 'Waagegasse Erfurt',
            'managed_by' => 1,
            'town' => 1,
            'address' => '{"remote_id":"genid-4205641db5894928b636fbc984941a62-b0","street":"Waagegasse","zip":"99084","city":"Erfurt","geo":{"latitude":50.97868297541305,"longitude":11.027608736826844}}',
            'offers' => null,
            'opening_hours' => null,
            'media' => null,
            'description' => 'La Waagegasse peut sembler peu spectaculaire au premier abord, mais il s\'agit d\'une rue remarquablement ancienne et très importante pour l\'histoire d\'Erfurt. En effet, tous les marchands qui voulaient passer par Erfurt et/ou faire du commerce à Erfurt passaient par ici. La rue est aussi large qu\'un carrosse, de sorte que l\'on pouvait faire passer chacun d\'eux individuellement. Chaque chariot était pesé ici, des taxes étaient prélevées en fonction de sa valeur et les marchandises étaient stockées pendant trois jours dans les maisons d\'empilage qui sont encore visibles aujourd\'hui.
Aujourd\'hui, la Waagegasse joue surtout un rôle de "chemin de traverse" entre la Michaelisstrasse et l\'Allerheiligenstrasse, d\'accès à l\'ancienne synagogue et, bien sûr, dans de nombreuses visites de la ville.',
            'slogan' => null,
            'accessibility_specification' => null,
            'parking_facility_near_by' => '1',
        ],
        [
            'uid' => 11,
            'pid' => 10,
            'sys_language_uid' => 2,
            'l18n_parent' => 5,
            'l10n_source' => 5,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/215230952334-yyno',
            'title' => 'Pont de l\'épicier',
            'managed_by' => 1,
            'town' => 1,
            'address' => '{"remote_id":"genid-a45a5606cd074d86bf242c9464d84171-b0","street":"Benediktsplatz 1","zip":"99084","city":"Erfurt","email":"service@erfurt-tourismus.de","phone":"+49 361 66 400","geo":{"latitude":50.978772,"longitude":11.031622}}',
            'offers' => null,
            'opening_hours' => null,
            'media' => '[{"mainImage":true,"type":"image","title":"Erfurt-Kraemerbruecke-11.jpg","description":"Kr\\u00e4merbr\\u00fccke in Erfurt","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/134362\\/Preview-1280x0\\/image","author":"Florian Trykowski","copyrightYear":2019,"license":{"type":"https:\\/\\/creativecommons.org\\/publicdomain\\/zero\\/1.0\\/deed.de","author":"https:\\/\\/home.ttgnet.de\\/ttg\\/projekte\\/10006\\/90136\\/Projektdokumente\\/Vergabe%20Rahmenvertrag%20Fotoproduktion"}},{"mainImage":false,"type":"image","title":"Erfurt-Kraemerbruecke.jpg","description":"Kr\\u00e4merbr\\u00fccke in Erfurt","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/134288\\/Preview-1280x0\\/image","author":"Florian Trykowski","copyrightYear":2019,"license":{"type":"https:\\/\\/creativecommons.org\\/publicdomain\\/zero\\/1.0\\/deed.de","author":"https:\\/\\/home.ttgnet.de\\/ttg\\/projekte\\/10006\\/90136\\/Projektdokumente\\/Vergabe%20Rahmenvertrag%20Fotoproduktion"}},{"mainImage":false,"type":"image","title":"Erfurt-Kraemerbruecke-11.jpg","description":"Kr\\u00e4merbr\\u00fccke in Erfurt","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/134362\\/Preview-1280x0\\/image","author":"Florian Trykowski","copyrightYear":2019,"license":{"type":"https:\\/\\/creativecommons.org\\/publicdomain\\/zero\\/1.0\\/deed.de","author":"https:\\/\\/home.ttgnet.de\\/ttg\\/projekte\\/10006\\/90136\\/Projektdokumente\\/Vergabe%20Rahmenvertrag%20Fotoproduktion"}},{"mainImage":false,"type":"image","title":"Erfurt-Kraemerbruecke-13.jpg","description":"Ansicht der Kr\\u00e4merbr\\u00fccke, Erfurt","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/652340\\/Preview-1280x0\\/image","author":"Florian Trykowski","copyrightYear":2019,"license":{"type":"https:\\/\\/creativecommons.org\\/publicdomain\\/zero\\/1.0\\/deed.de","author":"https:\\/\\/home.ttgnet.de\\/ttg\\/projekte\\/10006\\/90136\\/Projektdokumente\\/Vergabe%20Rahmenvertrag%20Fotoproduktion"}}]',
            'description' => 'Le pont de l’épicier est un des symboles de la ville d’Erfurt, le plus grand pont habité en continu d’Europe. A l’origine, le pont de l’épicier faisait 120 m de long et comptait 62 maisons étroites, qui furent plus tard regroupées en 32 maisons. Sur le pont de l’épicier se trouvent des galeries et des petites échoppes proposant des étoffes à motifs bleu indigo de Thuringe, des céramiques peintes main, du verre de Lauscha, des bijoux et des sculptures en bois.',
            'slogan' => null,
            'accessibility_specification' => '{"accessibilityCertificationStatus":"AccessibilityChecked","certificationAccessibilityDeaf":"None","certificationAccessibilityMental":"None","certificationAccessibilityPartiallyDeaf":"None","certificationAccessibilityPartiallyVisual":"Info","certificationAccessibilityVisual":"None","certificationAccessibilityWalking":"Info","certificationAccessibilityWheelchair":"Info","accessibilitySearchCriteria":{"facilityAccessibilityWalking":["AllRoomsStepFreeAccess","HingedGrabRailToilet","LateralAccessibleToilet","StepFreeAccess","ToiletsPeopleWithDisabilities","NinetyCMWidthPassageWays","SpecialOffersWalkingImpairment","SpecialOffersWheelchairUsers"],"facilityAccessibilityVisual":["AssistanceDogsWelcome","VisuallyContrastingStepEdges","OffersInPictoralLanguage","SpecialOffersBlindPeople","SpecialOffersVisualImpairment","TactileOffers"],"facilityAccessibilityDeaf":["AudioInductionLoop","SpecialOffersHearingImpairment"],"facilityAccessibilityMental":["InformationWithPictogramsOrPictures"]}}',
            'parking_facility_near_by' => '1,2',
        ],
        [
            'uid' => 12,
            'pid' => 10,
            'sys_language_uid' => 2,
            'l18n_parent' => 6,
            'l10n_source' => 6,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/052821473718-oxfq',
            'title' => 'Wenigemarkt Erfurt',
            'managed_by' => 1,
            'town' => 1,
            'address' => '{"remote_id":"genid-0f944fd40aa04d3d85374be0fe18c485-b0","street":"Wenigermarkt","zip":"99084","city":"Erfurt","geo":{"latitude":50.97859562923252,"longitude":11.031994832523964}}',
            'offers' => null,
            'opening_hours' => null,
            'media' => null,
            'description' => 'Le Wenigemarkt est situé à l\'entrée orientale du Krämerbrücke. Vous y trouverez une variété de cafés et de restaurants qui vous invitent à rester et à vous détendre.',
            'slogan' => null,
            'accessibility_specification' => null,
            'parking_facility_near_by' => '1,2',
        ],
        [
            'uid' => 13,
            'pid' => 10,
            'sys_language_uid' => 1,
            'l18n_parent' => 1,
            'l10n_source' => 1,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/835224016581-dara',
            'title' => 'Cathedral of St. Mary',
            'managed_by' => 1,
            'town' => 1,
            'address' => '{"remote_id":"genid-7bb7d92bd6624bdf84634c86e8acdbb4-b0","street":"Domstufen 1","zip":"99084","city":"Erfurt","email":"dominformation@domberg-erfurt.de","phone":"+49 361 6461265","geo":{"latitude":50.975955358589545,"longitude":11.023667024961856}}',
            'offers' => null,
            'opening_hours' => null,
            'media' => '[{"mainImage":true,"type":"image","title":"Erfurt-Dom und Severikirche-beleuchtet.jpg","description":"","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/5159216\\/Preview-1280x0\\/image","author":"","copyrightYear":2016,"license":{"type":"https:\\/\\/creativecommons.org\\/licenses\\/by\\/4.0\\/","author":""}},{"mainImage":false,"type":"image","title":"Erfurt-Dom-und-Severikirche.jpg","description":"Sicht auf Dom St. Marien, St. Severikirche sowie die davor liegenden Klostergeb\\u00e4ude und einem Ausschnitt des Biergartens umgeben von einem d\\u00e4mmerungsverf\\u00e4rten Himmel","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/5159186\\/Preview-1280x0\\/image","author":"","copyrightYear":2020,"license":{"type":"https:\\/\\/creativecommons.org\\/licenses\\/by\\/4.0\\/","author":""}},{"mainImage":false,"type":"image","title":"Erfurt-Dom und Severikirche-beleuchtet.jpg","description":"","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/5159216\\/Preview-1280x0\\/image","author":"","copyrightYear":2016,"license":{"type":"https:\\/\\/creativecommons.org\\/licenses\\/by\\/4.0\\/","author":""}}]',
            'description' => 'The late Gothic cathedral with its high-Gothic choir and Romanesque tower replaced the church built on this site for Bishop Boniface in 742. The central tower houses the "Gloriosa", the world’s largest medieval free-swinging bell. ',
            'slogan' => null,
            'accessibility_specification' => null,
            'parking_facility_near_by' => '1',
        ],
        [
            'uid' => 14,
            'pid' => 10,
            'sys_language_uid' => 1,
            'l18n_parent' => 2,
            'l10n_source' => 2,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/508431710173-wwne',
            'title' => 'Domplatz (Cathedral Square)',
            'managed_by' => 1,
            'town' => 1,
            'address' => '{"remote_id":"genid-443f86d2acdc469dad4b3588d31d0c49-b0","street":"Domplatz","zip":"99084","city":"Erfurt","geo":{"latitude":50.97694183291915,"longitude":11.023886024076779}}',
            'offers' => null,
            'opening_hours' => null,
            'media' => null,
            'description' => 'Domplatz square is only a few seconds\' walk from Kettenstrasse. Set against the majestic backdrop of the cathedral and the Church of St Severus, it boasts a host of attractive boutiques and a variety of restaurants and cafés. The square\'s daily market, which operates from 7am until 2pm sells fresh regional produce including fruit and vegetables, meat and sausage products and many other tasty treats.
From Domplatz square, Marktstrasse - which follows the centuries-old trading route the Via Regia - leads you back towards the city centre.',
            'slogan' => null,
            'accessibility_specification' => null,
            'parking_facility_near_by' => '1',
        ],
        [
            'uid' => 15,
            'pid' => 10,
            'sys_language_uid' => 1,
            'l18n_parent' => 3,
            'l10n_source' => 3,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/165868194223-zmqf',
            'title' => 'Old Synagogue',
            'managed_by' => 1,
            'town' => 1,
            'address' => '{"remote_id":"genid-28b33237f71b41e3ad54a99e1da769b9-b0","street":"Waagegasse 8","zip":"99084","city":"Erfurt","email":"altesynagoge@erfurt.de","phone":"+49 361 6551520","fax":"+49 361 6551669","geo":{"latitude":50.978765,"longitude":11.029133}}',
            'offers' => '[{"types":["GuidedTourOffer"],"title":"","description":"","prices":[{"title":"","description":"","price":8,"currency":"EUR","rule":"PerPerson"},{"title":"","description":"","price":5,"currency":"EUR","rule":"PerPerson"}]},{"types":["EntryOffer"],"title":"","description":"","prices":[{"title":"","description":"","price":5,"currency":"EUR","rule":"PerPerson"},{"title":"","description":"","price":17,"currency":"EUR","rule":"PerGroup"},{"title":"","description":"","price":14.9,"currency":"EUR","rule":"PerPackage"},{"title":"","description":"","price":8,"currency":"EUR","rule":"PerPerson"}]}]',
            'opening_hours' => null,
            'media' => '[{"mainImage":true,"type":"image","title":"Erfurt-Alte Synagoge","description":"Frontaler Blick auf die Hausfront\\/Hausfassade im Innenhof mit Zugang \\u00fcber die Waagegasse","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/5099196\\/Preview-1280x0\\/image","author":"","copyrightYear":2009,"license":{"type":"https:\\/\\/creativecommons.org\\/licenses\\/by\\/4.0\\/","author":"F:\\\\Bilddatenbank\\\\Museen und Ausstellungen\\\\Alte Synagoge"}},{"mainImage":false,"type":"image","title":"Erfurt-Alte Synagoge","description":"Frontaler Blick auf die Hausfront\\/Hausfassade im Innenhof mit Zugang \\u00fcber die Waagegasse","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/5099196\\/Preview-1280x0\\/image","author":"","copyrightYear":2009,"license":{"type":"https:\\/\\/creativecommons.org\\/licenses\\/by\\/4.0\\/","author":"F:\\\\Bilddatenbank\\\\Museen und Ausstellungen\\\\Alte Synagoge"}}]',
            'description' => 'The Old Synagogue is one of very few preserved medieval synagogues in Europe. Thanks to the extensive preservation of the original structure, it has a special place in the history of art and architecture and is among the most impressive and highly rated architectural monuments in Erfurt and Thuringia. The synagogue was constructed during the Middle Ages on the "via regia", one of the major European trade routes, at the heart of the historical old quarter very close to the Merchants Bridge and the town hall. Many parts of the structure still remain today, including all four thick outer walls, the Roman­esque gemel window, the Gothic rose window and the entrance to the synagogue room. ',
            'slogan' => 'Highlight',
            'accessibility_specification' => '{"accessibilityCertificationStatus":"AccessibilityChecked","certificationAccessibilityDeaf":"None","certificationAccessibilityMental":"None","certificationAccessibilityPartiallyDeaf":"None","certificationAccessibilityPartiallyVisual":"Info","certificationAccessibilityVisual":"None","certificationAccessibilityWalking":"Info","certificationAccessibilityWheelchair":"Info","accessibilitySearchCriteria":{"facilityAccessibilityWalking":["AllRoomsStepFreeAccess","HingedGrabRailToilet","LateralAccessibleToilet","StepFreeAccess","ToiletsPeopleWithDisabilities","NinetyCMWidthPassageWays","SpecialOffersWalkingImpairment","SpecialOffersWheelchairUsers"],"facilityAccessibilityVisual":["AssistanceDogsWelcome","VisuallyContrastingStepEdges","OffersInPictoralLanguage","SpecialOffersBlindPeople","SpecialOffersVisualImpairment","TactileOffers"],"facilityAccessibilityDeaf":["AudioInductionLoop","SpecialOffersHearingImpairment"],"facilityAccessibilityMental":["InformationWithPictogramsOrPictures"]},"shortDescriptionAccessibilityDeaf":"English description of shortDescriptionAccessibilityDeaf","shortDescriptionAccessibilityMental":"English description of shortDescriptionAccessibilityMental","shortDescriptionAccessibilityVisual":"English description of shortDescriptionAccessibilityVisual","shortDescriptionAccessibilityWalking":"English description of shortDescriptionAccessibilityWalking"}',
            'parking_facility_near_by' => '1',
        ],
        [
            'uid' => 16,
            'pid' => 10,
            'sys_language_uid' => 1,
            'l18n_parent' => 4,
            'l10n_source' => 4,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/497839263245-edbm',
            'title' => 'Waagegasse Erfurt',
            'managed_by' => 1,
            'town' => 1,
            'address' => '{"remote_id":"genid-4205641db5894928b636fbc984941a62-b0","street":"Waagegasse","zip":"99084","city":"Erfurt","geo":{"latitude":50.97868297541305,"longitude":11.027608736826844}}',
            'offers' => null,
            'opening_hours' => null,
            'media' => null,
            'description' => 'The Waagegasse may seem unspectacular at first, but it is a remarkably old and very significant street for Erfurt\'s history. This is because all merchants who wanted to pass through Erfurt and/or trade in Erfurt passed through here. The street is as wide as a carriage, so that each one could be passed through individually. Each carriage was weighed here, taxes were levied according to its value and the goods were stored for three days in the stacking houses that are still visible today.
Today, the Waagegasse plays a role primarily as a "sneak path" between Michaelisstrasse and Allerheiligenstrasse, as access to the Old Synagogue and, of course, on numerous city tours.',
            'slogan' => null,
            'accessibility_specification' => null,
            'parking_facility_near_by' => '1',
        ],
        [
            'uid' => 17,
            'pid' => 10,
            'sys_language_uid' => 1,
            'l18n_parent' => 5,
            'l10n_source' => 5,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/215230952334-yyno',
            'title' => 'Merchants\' Bridge',
            'managed_by' => 1,
            'town' => 1,
            'address' => '{"remote_id":"genid-a45a5606cd074d86bf242c9464d84171-b0","street":"Benediktsplatz 1","zip":"99084","city":"Erfurt","email":"service@erfurt-tourismus.de","phone":"+49 361 66 400","geo":{"latitude":50.978772,"longitude":11.031622}}',
            'offers' => null,
            'opening_hours' => null,
            'media' => '[{"mainImage":true,"type":"image","title":"Erfurt-Kraemerbruecke-11.jpg","description":"Kr\\u00e4merbr\\u00fccke in Erfurt","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/134362\\/Preview-1280x0\\/image","author":"Florian Trykowski","copyrightYear":2019,"license":{"type":"https:\\/\\/creativecommons.org\\/publicdomain\\/zero\\/1.0\\/deed.de","author":"https:\\/\\/home.ttgnet.de\\/ttg\\/projekte\\/10006\\/90136\\/Projektdokumente\\/Vergabe%20Rahmenvertrag%20Fotoproduktion"}},{"mainImage":false,"type":"image","title":"Erfurt-Kraemerbruecke.jpg","description":"Kr\\u00e4merbr\\u00fccke in Erfurt","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/134288\\/Preview-1280x0\\/image","author":"Florian Trykowski","copyrightYear":2019,"license":{"type":"https:\\/\\/creativecommons.org\\/publicdomain\\/zero\\/1.0\\/deed.de","author":"https:\\/\\/home.ttgnet.de\\/ttg\\/projekte\\/10006\\/90136\\/Projektdokumente\\/Vergabe%20Rahmenvertrag%20Fotoproduktion"}},{"mainImage":false,"type":"image","title":"Erfurt-Kraemerbruecke-11.jpg","description":"Kr\\u00e4merbr\\u00fccke in Erfurt","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/134362\\/Preview-1280x0\\/image","author":"Florian Trykowski","copyrightYear":2019,"license":{"type":"https:\\/\\/creativecommons.org\\/publicdomain\\/zero\\/1.0\\/deed.de","author":"https:\\/\\/home.ttgnet.de\\/ttg\\/projekte\\/10006\\/90136\\/Projektdokumente\\/Vergabe%20Rahmenvertrag%20Fotoproduktion"}},{"mainImage":false,"type":"image","title":"Erfurt-Kraemerbruecke-13.jpg","description":"Ansicht der Kr\\u00e4merbr\\u00fccke, Erfurt","url":"https:\\/\\/cms.thuecat.org\\/o\\/adaptive-media\\/image\\/652340\\/Preview-1280x0\\/image","author":"Florian Trykowski","copyrightYear":2019,"license":{"type":"https:\\/\\/creativecommons.org\\/publicdomain\\/zero\\/1.0\\/deed.de","author":"https:\\/\\/home.ttgnet.de\\/ttg\\/projekte\\/10006\\/90136\\/Projektdokumente\\/Vergabe%20Rahmenvertrag%20Fotoproduktion"}}]',
            'description' => 'Another Erfurt landmark is the Merchants\' Bridge (Krämerbrücke), the longest series of inhabited buildings on any bridge in Europe. The Merchants\' Bridge is Erfurts most interesting secular construction, initially in wood but rebuilt in stone in 1325. There were originally 62 narrow buildings along its 120-metre length, but subsequent redevelopment left just 32 buildings. Of what was once a pair of bridgehead churches, only the Church of St. Aegidius remains at the eastern end of the bridge today. The Merchants\' Bridge is lined with galleries, cafés and boutiques offering traditional crafts, Thuringian blue printed fabrics, hand-painted ceramics, handblown glassware, jewellery, wood carvings, antiques and delicious Thuringian specialities - perfect for browsing.',
            'slogan' => null,
            'accessibility_specification' => '{"accessibilityCertificationStatus":"AccessibilityChecked","certificationAccessibilityDeaf":"None","certificationAccessibilityMental":"None","certificationAccessibilityPartiallyDeaf":"None","certificationAccessibilityPartiallyVisual":"Info","certificationAccessibilityVisual":"None","certificationAccessibilityWalking":"Info","certificationAccessibilityWheelchair":"Info","accessibilitySearchCriteria":{"facilityAccessibilityWalking":["AllRoomsStepFreeAccess","HingedGrabRailToilet","LateralAccessibleToilet","StepFreeAccess","ToiletsPeopleWithDisabilities","NinetyCMWidthPassageWays","SpecialOffersWalkingImpairment","SpecialOffersWheelchairUsers"],"facilityAccessibilityVisual":["AssistanceDogsWelcome","VisuallyContrastingStepEdges","OffersInPictoralLanguage","SpecialOffersBlindPeople","SpecialOffersVisualImpairment","TactileOffers"],"facilityAccessibilityDeaf":["AudioInductionLoop","SpecialOffersHearingImpairment"],"facilityAccessibilityMental":["InformationWithPictogramsOrPictures"]},"shortDescriptionAccessibilityDeaf":"English description of shortDescriptionAccessibilityDeaf","shortDescriptionAccessibilityMental":"English description of shortDescriptionAccessibilityMental","shortDescriptionAccessibilityVisual":"English description of shortDescriptionAccessibilityVisual","shortDescriptionAccessibilityWalking":"English description of shortDescriptionAccessibilityWalking"}',
            'parking_facility_near_by' => '1,2',
        ],
        [
            'uid' => 18,
            'pid' => 10,
            'sys_language_uid' => 1,
            'l18n_parent' => 6,
            'l10n_source' => 6,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/052821473718-oxfq',
            'title' => 'Wenigemarkt Erfurt',
            'managed_by' => 1,
            'town' => 1,
            'address' => '{"remote_id":"genid-0f944fd40aa04d3d85374be0fe18c485-b0","street":"Wenigermarkt","zip":"99084","city":"Erfurt","geo":{"latitude":50.97859562923252,"longitude":11.031994832523964}}',
            'offers' => null,
            'opening_hours' => null,
            'media' => null,
            'description' => 'The Wenigemarkt is located at the eastern entrance of the Krämerbrücke. Here you will find a variety of cafes and restaurants that invite you to stay and relax.',
            'slogan' => null,
            'accessibility_specification' => null,
            'parking_facility_near_by' => '1,2',
        ],
    ],
    'tx_thuecat_town' => [
        [
            'uid' => 1,
            'pid' => 10,
            'sys_language_uid' => 0,
            'l10n_source' => 0,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/043064193523-jcyt',
            'title' => 'Erfurt',
            'managed_by' => 1,
            'description' => 'Krämerbrücke, Dom, Alte Synagoge – die Thüringer Landeshauptstadt Erfurt hat viele Kulturschätze. Und ein wunderbar junges, studentisches Flair.Eine gute Mischung für alle, die beim Schlendern und Bummeln gerne Städte entdecken: Denn in Erfurt findet man einen wunderbaren mittelalterlichen Stadtkern – mit vielen netten Läden, Cafès und Restaurants. Urlauber wie Einheimische bummeln durch die Gassen der Altstadt, aus allen Ecken wispern Geschichte und alte Geschichten. Stolze historische Bügerhäuser bilden eine der schönsten Altstädte Europas, mittendrin das neugotische Rathaus aus den 1870er-Jahren am Fischmarkt, die spitztürmige St. Severikirche und der mächtige Dom, 1117 erstmals urkundlich erwähnt – auf seiner schier endlosen, kaskadenförmigen Freitreppe chillen Jung und Alt gern in der Abendsonne. Ehe sie weiter ziehen zum Tagesausklang in eine der coolen Kneipen und Bars (Tipp: Oma Lilo oder Cafè Hilgenfeld), in die Wein-Destille am benachbarten Petersberg oder in eins der lässigen Restaurants (Tipp: Mathilda oder Ballenberger), wo zum freundlichen Miteinander eine frische und moderne Küche serviert wird.In Erfurt pulsiert das Leben, lassen Sie sich einfach treiben. Von Ihrer Neugierde ...',
        ],
    ],
    'tx_thuecat_organisation' => [
        [
            'uid' => 1,
            'pid' => 10,
            'sys_language_uid' => 0,
            'l10n_source' => 0,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/018132452787-ngbe',
            'title' => 'Erfurt Tourismus und Marketing GmbH',
            'description' => 'Die Erfurt Tourismus & Marketing GmbH (ETMG) wurde 1997 als offizielle Organisation zur Tourismusförderung in der Landeshauptstadt Erfurt gegründet und nahm am 01.01.1998 die Geschäftstätigkeit auf.

Zu den Aufgaben zählen die kommunale Tourismusförderung als wesentliches Instrument der Wirtschafts- und Stadtentwicklung der Landeshauptstadt Erfurt, die Positionierung der Stadt Erfurt auf dem nationalen und internationalen Tourismusmarkt als dynamische und sympathische Landeshauptstadt, attraktives Städtereiseziel und Tagungsstandort, die Vervollkommnung des touristischen Serviceangebotes entsprechend den Bedürfnissen der individuellen Gäste und der Tourismuswirtschaft und das Betreiben der Erfurt Tourist Information.

Im Januar 2009 wurde das Marketing für die Landeshauptstadt Erfurt an die ETMG übertragen und neu geordnet. Die Hauptaufgaben im Stadtmarketing liegen darin, die Wahrnehmung der Stadt in folgenden Bereichen zu verstärken: traditionsreicher und innovativer Wirtschaftsstandort, lebendiger und kreativer Wissenschaftsstandort, attraktiver Wohnstandort mit Flair und Sportstandort mit exzellenten Bedingungen für Nachwuchs- und Spitzensportler.

Gesellschafter: Stadt Erfurt

Geschäftsführerin: Frau Dr. Carmen Hildebrandt

Aufsichtsratsvorsitzender: Herr Dominik Kordon

Mitarbeiter: ca. 30 Angestellte, 4 Auszubildende',
        ],
    ],
    'tx_thuecat_parking_facility' => [
        [
            'uid' => 1,
            'pid' => 10,
            'sys_language_uid' => 0,
            'l18n_parent' => 0,
            'l10n_source' => 0,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/396420044896-drzt',
            'title' => 'Parkhaus Domplatz',
            'managed_by' => 1,
            'town' => 0,
            'address' => '{"remote_id":"genid-2c9c8a1b44cc404ebe32e34cdbb87884-b0","street":"Bechtheimer Str. 1","zip":"99084","city":"Erfurt","email":"info@stadtwerke-erfurt.de","phone":"+49 361 5640","geo":{"latitude":50.977648905044,"longitude":11.022127985954299}}',
            'offers' => '[{"types":["ParkingFee"],"title":"","description":"","prices":[{"title":"","description":"","price":35,"currency":"EUR","rule":"PerCar"}]},{"types":["ParkingFee"],"title":"","description":"","prices":[{"title":"","description":"","price":1.5,"currency":"EUR","rule":"PerCar"}]},{"types":["ParkingFee"],"title":"","description":"","prices":[{"title":"","description":"","price":10,"currency":"EUR","rule":"PerCar"}]},{"types":["ParkingFee"],"title":"","description":"","prices":[{"title":"","description":"","price":50,"currency":"EUR","rule":"PerCar"}]}]',
            'opening_hours' => '[{"opens":"07:00:00","closes":"22:00:00","daysOfWeek":["Saturday","Friday","Thursday","Tuesday","Monday","Wednesday"]},{"opens":"09:00:00","closes":"22:00:00","daysOfWeek":["Sunday","PublicHolidays"]}]',
            'media' => null,
            'description' => 'Das Parkhaus Domplatz befindet sich unmittelbar unterhalb der Zitadelle Petersberg am nördlichen Rand des Domplatzes. Durch die zentrale Lage ist es ein idealer Ausgangspunkt für Stadtbummel und Erkundungen des Zentrums, des Petersbergs und des Andreasviertels.',
        ],
        [
            'uid' => 2,
            'pid' => 10,
            'sys_language_uid' => 0,
            'l18n_parent' => 0,
            'l10n_source' => 0,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/440055527204-ocar',
            'title' => 'Q-Park Anger 1 Parkhaus',
            'managed_by' => 1,
            'town' => 1,
            'address' => '{"remote_id":"genid-9de58329a0684feaa8b9b5ea70621af8-b0","street":"Anger 1","zip":"99084","city":"Erfurt","email":"servicecenter@q-park.de","phone":"+49 218 18190290","geo":{"latitude":50.977999330565794,"longitude":11.037503264052475}}',
            'offers' => '[{"types":["ParkingFee"],"title":"","description":"","prices":[{"title":"","description":"","price":2.2,"currency":"EUR","rule":"PerCar"}]},{"types":["ParkingFee"],"title":"","description":"","prices":[{"title":"","description":"","price":1,"currency":"EUR","rule":"PerCar"}]},{"types":["ParkingFee"],"title":"","description":"","prices":[{"title":"","description":"","price":13,"currency":"EUR","rule":"PerCar"}]}]',
            'opening_hours' => null,
            'media' => null,
            'description' => 'Der Q-Park liegt direkt hinter dem Kaufhaus Anger 1 im Erfurter Stadtzentrum und ist über Juri-Gagarin-Ring/Meyfartstraße zu erreichen. Durch die direkte Anbindung an den Stadtring, ist das Parkhaus gut von außerhalb über Schnellstraßen und Autobahnen zu erreichen und befindet sich gleichzeitig im unmittelbaren modernen Zentrum Erfurts.',
        ],
        [
            'uid' => 3,
            'pid' => 10,
            'sys_language_uid' => 2,
            'l18n_parent' => 1,
            'l10n_source' => 1,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/396420044896-drzt',
            'title' => 'Parking Domplatz',
            'managed_by' => 1,
            'town' => 0,
            'address' => '{"remote_id":"genid-2c9c8a1b44cc404ebe32e34cdbb87884-b0","street":"Bechtheimer Str. 1","zip":"99084","city":"Erfurt","email":"info@stadtwerke-erfurt.de","phone":"+49 361 5640","geo":{"latitude":50.977648905044,"longitude":11.022127985954299}}',
            'offers' => '[{"types":["ParkingFee"],"title":"","description":"","prices":[{"title":"","description":"","price":35,"currency":"EUR","rule":"PerCar"}]},{"types":["ParkingFee"],"title":"","description":"","prices":[{"title":"","description":"","price":1.5,"currency":"EUR","rule":"PerCar"}]},{"types":["ParkingFee"],"title":"","description":"","prices":[{"title":"","description":"","price":10,"currency":"EUR","rule":"PerCar"}]},{"types":["ParkingFee"],"title":"","description":"","prices":[{"title":"","description":"","price":50,"currency":"EUR","rule":"PerCar"}]}]',
            'opening_hours' => '[{"opens":"07:00:00","closes":"22:00:00","daysOfWeek":["Saturday","Friday","Thursday","Tuesday","Monday","Wednesday"]},{"opens":"09:00:00","closes":"22:00:00","daysOfWeek":["Sunday","PublicHolidays"]}]',
            'media' => null,
            'description' => 'Le parking à étages de la Domplatz est situé juste en dessous de la citadelle de Petersberg, sur le bord nord de la Domplatz. Son emplacement central en fait un point de départ idéal pour se promener dans la ville et explorer le centre, le Petersberg et l\'Andreasviertel.',
        ],
        [
            'uid' => 4,
            'pid' => 10,
            'sys_language_uid' => 2,
            'l18n_parent' => 2,
            'l10n_source' => 2,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/440055527204-ocar',
            'title' => 'Q-Park Anger 1 parking à étages',
            'managed_by' => 1,
            'town' => 1,
            'address' => '{"remote_id":"genid-9de58329a0684feaa8b9b5ea70621af8-b0","street":"Anger 1","zip":"99084","city":"Erfurt","email":"servicecenter@q-park.de","phone":"+49 218 18190290","geo":{"latitude":50.977999330565794,"longitude":11.037503264052475}}',
            'offers' => '[{"types":["ParkingFee"],"title":"","description":"","prices":[{"title":"","description":"","price":2.2,"currency":"EUR","rule":"PerCar"}]},{"types":["ParkingFee"],"title":"","description":"","prices":[{"title":"","description":"","price":1,"currency":"EUR","rule":"PerCar"}]},{"types":["ParkingFee"],"title":"","description":"","prices":[{"title":"","description":"","price":13,"currency":"EUR","rule":"PerCar"}]}]',
            'opening_hours' => null,
            'media' => null,
            'description' => 'Le Q-Park est situé directement derrière le grand magasin Anger 1 dans le centre-ville d\'Erfurt et peut être atteint par la Juri-Gagarin-Ring/Meyfartstraße.',
        ],
        [
            'uid' => 5,
            'pid' => 10,
            'sys_language_uid' => 1,
            'l18n_parent' => 1,
            'l10n_source' => 1,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/396420044896-drzt',
            'title' => 'Car park Domplatz',
            'managed_by' => 1,
            'town' => 0,
            'address' => '{"remote_id":"genid-2c9c8a1b44cc404ebe32e34cdbb87884-b0","street":"Bechtheimer Str. 1","zip":"99084","city":"Erfurt","email":"info@stadtwerke-erfurt.de","phone":"+49 361 5640","geo":{"latitude":50.977648905044,"longitude":11.022127985954299}}',
            'offers' => '[{"types":["ParkingFee"],"title":"","description":"","prices":[{"title":"","description":"","price":35,"currency":"EUR","rule":"PerCar"}]},{"types":["ParkingFee"],"title":"","description":"","prices":[{"title":"","description":"","price":1.5,"currency":"EUR","rule":"PerCar"}]},{"types":["ParkingFee"],"title":"","description":"","prices":[{"title":"","description":"","price":10,"currency":"EUR","rule":"PerCar"}]},{"types":["ParkingFee"],"title":"","description":"","prices":[{"title":"","description":"","price":50,"currency":"EUR","rule":"PerCar"}]}]',
            'opening_hours' => '[{"opens":"07:00:00","closes":"22:00:00","daysOfWeek":["Saturday","Friday","Thursday","Tuesday","Monday","Wednesday"]},{"opens":"09:00:00","closes":"22:00:00","daysOfWeek":["Sunday","PublicHolidays"]}]',
            'media' => null,
            'description' => 'The Domplatz multi-storey car park is located directly below the Petersberg Citadel on the northern edge of the Domplatz. Its central location makes it an ideal starting point for strolling through the city and exploring the centre, the Petersberg and the Andreasviertel.',
        ],
        [
            'uid' => 6,
            'pid' => 10,
            'sys_language_uid' => 1,
            'l18n_parent' => 2,
            'l10n_source' => 2,
            'l10n_state' => null,
            'remote_id' => 'https://thuecat.org/resources/440055527204-ocar',
            'title' => 'Q-Park Anger 1 multi-storey car park',
            'managed_by' => 1,
            'town' => 1,
            'address' => '{"remote_id":"genid-9de58329a0684feaa8b9b5ea70621af8-b0","street":"Anger 1","zip":"99084","city":"Erfurt","email":"servicecenter@q-park.de","phone":"+49 218 18190290","geo":{"latitude":50.977999330565794,"longitude":11.037503264052475}}',
            'offers' => '[{"types":["ParkingFee"],"title":"","description":"","prices":[{"title":"","description":"","price":2.2,"currency":"EUR","rule":"PerCar"}]},{"types":["ParkingFee"],"title":"","description":"","prices":[{"title":"","description":"","price":1,"currency":"EUR","rule":"PerCar"}]},{"types":["ParkingFee"],"title":"","description":"","prices":[{"title":"","description":"","price":13,"currency":"EUR","rule":"PerCar"}]}]',
            'opening_hours' => null,
            'media' => null,
            'description' => 'The Q-Park is located directly behind the department store Anger 1 in Erfurt\'s city centre and can be reached via Juri-Gagarin-Ring/Meyfartstraße.',
        ],
    ],
];
